import { useEffect, useMemo, useState } from 'react';
import { Cable, CirclePower, Cpu, Disc3, Layers3, Library, Radio, SlidersHorizontal, Waves } from 'lucide-react';
import { SloopDeviceSession, type SessionState } from '../core/SloopDeviceSession';
import { WebMidiSloopTransport } from '../core/WebMidiSloopTransport';
import { VirtualSloopTransport } from '../core/VirtualSloopTransport';
import type { MidiPortDescriptor, MidiPortSelection } from '../core/portTypes';
import { getAutomationKeys, getAutomationValue } from '../features/effects/automationStore';
import { shouldPlayStep } from '../features/sequencer/sequenceRuntime';
import { ConnectionSetup } from './components/ConnectionSetup';
import { DevicePanel } from './components/DevicePanel';
import { SampleEditor } from './components/SampleEditor';
import { Sequencer } from './components/Sequencer';
import { MixerPanel } from './components/MixerPanel';
import { LibraryPanel } from './components/LibraryPanel';
import { EffectsRack } from './components/EffectsRack';
import { ArrangerPanel } from './components/ArrangerPanel';

const EMPTY_STATE:SessionState={loading:false,connected:false,selectedTrack:0,tracks:[],descriptors:[],values:{},steps:[],drumSteps:[],sampleSlots:[],soloMask:0};
const DRUM_NOTES=[36,38,42,46,41,43,45,49,51,39,37,54,56,75,81,82];
export function App(){
 const[mode,setMode]=useState<'hardware'|'virtual'>('virtual'),[state,setState]=useState<SessionState>(EMPTY_STATE),[status,setStatus]=useState('Offline workspace ready'),[ports,setPorts]=useState<MidiPortDescriptor[]>([]),[selection,setSelection]=useState<MidiPortSelection>({}),[scanning,setScanning]=useState(false),[connectionError,setConnectionError]=useState<string>(),[playing,setPlaying]=useState(false),[playhead,setPlayhead]=useState(-1);
 const transport=useMemo(()=>mode==='hardware'?new WebMidiSloopTransport(selection):new VirtualSloopTransport(),[mode,selection.inputId,selection.outputId]);const session=useMemo(()=>new SloopDeviceSession(transport),[transport]);
 useEffect(()=>{const unsubscribe=session.subscribe(setState);setState(session.snapshot());return()=>unsubscribe();},[session]);useEffect(()=>()=>{void session.disconnect();},[session]);
 const bpmDescriptor=state.descriptors.find(d=>d.scope===1&&d.label.toUpperCase()==='BPM'),bpm=bpmDescriptor?state.values[`1:${bpmDescriptor.id}`]??bpmDescriptor.defaultValue:120;
 useEffect(()=>{if(!playing||mode!=='virtual'||!state.connected||!(transport instanceof VirtualSloopTransport)){setPlayhead(-1);return;}const count=Math.max(1,state.info?.stepCount??64),ms=60000/Math.max(20,bpm)/4;let current=-1;const tick=()=>{current=(current+1)%count;setPlayhead(current);for(const key of getAutomationKeys()){const raw=getAutomationValue(key,current);if(raw==null)continue;const[scopeText,idText]=key.split(':'),scope=Number(scopeText) as 0|1,id=Number(idText),descriptor=state.descriptors.find(d=>d.scope===scope&&d.id===id);if(!descriptor)continue;const value=Math.round(descriptor.min+(raw/127)*(descriptor.max-descriptor.min));void session.setParameter(scope,id,value);}if(!shouldPlayStep(state.selectedTrack))return;if(state.selectedTrack===3){const d=state.drumSteps.find(s=>s.index===current);d?.on.forEach((on,lane)=>{if(on)transport.audition(midiToTone(DRUM_NOTES[lane]??36),'32n');});}else{const s=state.steps.find(x=>x.index===current);s?.notes.forEach(note=>transport.audition(midiToTone(note),'16n'));}};tick();const timer=window.setInterval(tick,ms);return()=>window.clearInterval(timer);},[playing,mode,state.connected,state.info?.stepCount,state.selectedTrack,state.steps,state.drumSteps,state.descriptors,bpm,transport,session]);
 async function connect(){setConnectionError(undefined);try{setStatus(mode==='hardware'?'Requesting Web MIDI + SysEx…':'Starting virtual audio engine…');await session.connect();setStatus(mode==='hardware'?'SLOOP connected · WATCH live sync active':'Virtual SLOOP online');}catch(error){const message=error instanceof Error?error.message:'Connection failed';setStatus(message);setConnectionError(message);}}
 async function disconnect(){setPlaying(false);await session.disconnect();setStatus('Disconnected');}async function switchMode(){setPlaying(false);await session.disconnect().catch(()=>undefined);setState(EMPTY_STATE);setConnectionError(undefined);setMode(current=>current==='hardware'?'virtual':'hardware');setStatus('Mode changed · connect when ready');}
 async function scanMidi(){setScanning(true);setConnectionError(undefined);try{const found=await WebMidiSloopTransport.listPorts();setPorts(found);const input=found.find(p=>p.type==='input'&&/m-vave|fm-1|sloop/i.test(`${p.manufacturer} ${p.name}`)),output=found.find(p=>p.type==='output'&&/m-vave|fm-1|sloop/i.test(`${p.manufacturer} ${p.name}`));setSelection(current=>({inputId:current.inputId??input?.id,outputId:current.outputId??output?.id}));setStatus(`${found.length} MIDI ports found`);}catch(error){const message=error instanceof Error?error.message:'Unable to scan MIDI ports';setConnectionError(message);setStatus(message);}finally{setScanning(false);}}
 function audition(note:number){if(transport instanceof VirtualSloopTransport)transport.audition(midiToTone(note),'8n');}
 return <main className="min-h-screen"><header className="sticky top-0 z-30 border-b border-white/8 bg-[#0c0f11]/90 px-4 py-3 backdrop-blur-xl"><div className="mx-auto flex max-w-[1900px] items-center justify-between gap-4"><div className="flex items-center gap-3"><div className="grid h-9 w-9 place-items-center rounded-md border border-emerald-300/30 bg-emerald-300/10"><Waves className="text-emerald-300" size={19}/></div><div><b>SloopUI</b><div className="text-[10px] uppercase tracking-[.2em] text-zinc-500">FM-1 hardware studio · M0–M4</div></div></div><div className="flex items-center gap-2"><div className="hidden text-right md:block"><div className={`text-xs ${state.connected?'text-emerald-300':state.error||connectionError?'text-rose-300':'text-zinc-400'}`}>{state.loading?'Loading device…':state.error??connectionError??status}</div><div className="text-[10px] text-zinc-600">{state.info?`${state.info.firmware} · protocol v${state.info.protocolVersion}`:mode==='hardware'?'Direct Web MIDI / SysEx':'Tone.js virtual device'}</div></div><button onClick={()=>void switchMode()} className="tool"><Cpu size={14} className="mr-1 inline"/>{mode.toUpperCase()}</button><button disabled={state.loading} onClick={()=>void(state.connected?disconnect():connect())} className={`rounded px-3 py-2 text-xs font-black ${state.connected?'bg-emerald-300 text-black':'bg-white text-black'} disabled:opacity-40`}><CirclePower size={14} className="mr-1 inline"/>{state.connected?'DISCONNECT':'CONNECT'}</button></div></div></header>
 <div className="mx-auto grid max-w-[1900px] gap-4 p-4 xl:grid-cols-[190px_minmax(0,1fr)]"><aside className="hardware-panel sticky top-20 hidden h-fit rounded-xl p-3 xl:block"><div className="mb-2 px-2 text-[10px] font-bold tracking-[.2em] text-zinc-600">STUDIO</div><Nav icon={<SlidersHorizontal size={15}/>} label="Device" href="#device"/><Nav icon={<Cable size={15}/>} label="Mixer" href="#mixer"/><Nav icon={<Layers3 size={15}/>} label="Sequence" href="#sequence"/><Nav icon={<Layers3 size={15}/>} label="Arranger" href="#arranger"/><Nav icon={<Disc3 size={15}/>} label="Samples" href="#samples"/><Nav icon={<Radio size={15}/>} label="Effects" href="#effects"/><Nav icon={<Library size={15}/>} label="Library" href="#library"/></aside><div className="space-y-4">{state.connected?<><div id="device"><DevicePanel state={state} session={session}/></div><MixerPanel state={state} session={session}/><Sequencer state={state} session={session} virtual={mode==='virtual'} playing={playing} playhead={playhead} onTogglePlay={()=>setPlaying(v=>!v)} onAudition={audition}/><ArrangerPanel state={state} session={session}/><SampleEditor state={state} session={session}/><EffectsRack state={state} session={session} virtual={mode==='virtual'}/><LibraryPanel state={state} session={session}/></>:<ConnectionSetup mode={mode} ports={ports} selection={selection} scanning={scanning} error={connectionError} onScan={()=>void scanMidi()} onSelectionChange={setSelection} onConnect={()=>void connect()}/>}</div></div></main>;
}
function Nav({icon,label,href}:{icon:React.ReactNode;label:string;href:string}){return <a href={href} className="mb-1 flex w-full items-center gap-2 rounded px-3 py-2 text-left text-sm text-zinc-300 hover:bg-white/5">{icon}{label}</a>;}function midiToTone(note:number){const names=['C','C#','D','D#','E','F','F#','G','G#','A','A#','B'];return`${names[note%12]}${Math.floor(note/12)-1}`;}
