import { RefreshCw, ZoomIn } from 'lucide-react';
import { useState } from 'react';
import type { SessionState, SloopDeviceSession } from '../../core/SloopDeviceSession';
import { SloopCommand } from '../../protocol/sloopProtocol';
const NAMES=['SYNTH 1','SYNTH 2','SYNTH 3','DRUMS'];
export function ArrangerPanel({state,session}:{state:SessionState;session:SloopDeviceSession}){
 const [lanes,setLanes]=useState<boolean[][]>(Array.from({length:4},()=>[]));const [zoom,setZoom]=useState(1);const [grid,setGrid]=useState(4);const [loading,setLoading]=useState(false);
 async function refresh(){const count=state.info?.stepCount??64;setLoading(true);try{const next=Array.from({length:4},()=>Array(count).fill(false)) as boolean[][];for(let track=0;track<3;track++)for(let i=0;i<count;i++){const r=await session.request(SloopCommand.TrackStep,[track,i]);next[track][i]=(r.data[3]??0)>0;}for(let i=0;i<count;i++){const r=await session.request(SloopCommand.DrumStep,[i]);next[3][i]=!!((r.data[1]??0)||(r.data[2]??0)||(r.data[3]??0));}setLanes(next);}finally{setLoading(false);}}
 const count=state.info?.stepCount??64;return <section className="hardware-panel rounded-xl p-4" id="arranger"><div className="mb-3 flex flex-wrap items-center justify-between gap-2"><div><b>Arranger</b><span className="ml-2 text-xs text-zinc-500">4-track overview · bar/beat ruler · grid snapping reference</span></div><div className="flex items-center gap-2"><label className="field flex items-center gap-1"><ZoomIn size={11}/><input type="range" min={.6} max={2.5} step={.1} value={zoom} onChange={e=>setZoom(Number(e.target.value))}/></label><select className="select" value={grid} onChange={e=>setGrid(Number(e.target.value))}><option value={1}>1/16 grid</option><option value={2}>1/8 grid</option><option value={4}>1/4 grid</option><option value={8}>1/2 grid</option></select><button disabled={loading} onClick={()=>void refresh()} className="tool"><RefreshCw size={11} className="mr-1 inline"/>{loading?'Reading…':'Read device'}</button></div></div><div className="overflow-auto rounded-lg border border-white/8 bg-black/25"><div style={{width:`${Math.max(900,count*20*zoom)}px`}}><div className="grid h-6 items-center border-b border-white/8 text-[8px] text-zinc-600" style={{gridTemplateColumns:`100px repeat(${count},1fr)`}}><span className="px-2">TRACK</span>{Array.from({length:count},(_,i)=><span key={i} className={`${i%grid===0?'border-l border-white/15':''} px-0.5`}>{i%4===0?i/4+1:''}</span>)}</div>{NAMES.map((name,track)=><div key={name} className="grid h-12 items-stretch border-b border-white/5" style={{gridTemplateColumns:`100px repeat(${count},1fr)`}}><button onClick={()=>void session.selectTrack(track)} className={`sticky left-0 z-10 px-2 text-left text-[10px] font-bold ${state.selectedTrack===track?'bg-emerald-300/15 text-emerald-200':'bg-zinc-950 text-zinc-500'}`}>{name}</button>{Array.from({length:count},(_,i)=><span key={i} className={`border-l ${i%grid===0?'border-white/10':'border-white/[.025]'} ${lanes[track]?.[i]?(track===3?'bg-rose-300/45':'bg-emerald-300/40'):''}`}/>)}</div>)}</div></div></section>;
}
