import { useMemo, useState } from 'react';
import type { ParameterDescriptor, SessionState, SloopDeviceSession } from '../../core/SloopDeviceSession';
import { ParameterControl } from './ParameterControl';
import { SynthVisualizer, type SynthVisualKind } from './SynthVisualizers';

const TRACK_NAMES=['SYNTH 1','SYNTH 2','SYNTH 3','DRUMS'];
type GroupName='OSC / SOURCE'|'FILTER'|'AMP ENV'|'MOD / SHAPE'|'FX / SPACE'|'PERFORMANCE'|'GLOBAL';
export function DevicePanel({state,session}:{state:SessionState;session:SloopDeviceSession}){
 const[page,setPage]=useState<'synth'|'global'>('synth');const parameters=state.descriptors.filter(d=>d.scope===0),globals=state.descriptors.filter(d=>d.scope===1);const engine=state.tracks[state.selectedTrack]?.engine??0,title=state.selectedTrack===3?'DRUMS':state.info?.engineNames[engine]??'Device';
 const groups=useMemo(()=>groupDescriptors(page==='synth'?parameters:globals,page==='global'),[parameters,globals,page]);
 const featured=page==='synth'&&state.selectedTrack<3?(['FILTER','AMP ENV','MOD / SHAPE'] as GroupName[]).map(name=>groups.find(g=>g.name===name)).filter(Boolean) as {name:GroupName;items:ParameterDescriptor[]}[]:[];const rest=groups.filter(g=>!featured.some(f=>f.name===g.name));
 return <section className="hardware-panel rounded-xl p-3"><div className="mb-3 flex flex-wrap items-center justify-between gap-2 border-b border-white/8 pb-2"><div><div className="text-[9px] font-black tracking-[.24em] text-emerald-300">SLOOP // FM-1</div><div className="flex items-baseline gap-2"><h2 className="text-base font-semibold">{title}</h2><span className="text-[9px] text-zinc-600">live firmware controls</span></div></div><div className="flex flex-wrap items-center gap-1">{state.tracks.map((track,index)=><button key={track.index} onClick={()=>void session.selectTrack(index)} className={`rounded border px-2.5 py-1 text-[10px] font-black ${index===state.selectedTrack?'border-emerald-300/60 bg-emerald-300/15 text-emerald-100':'border-white/10 text-zinc-500'}`}>{TRACK_NAMES[index]}{track.mute?' · M':''}</button>)}<span className="mx-1 h-5 w-px bg-white/10"/><button onClick={()=>setPage('synth')} className={`tool ${page==='synth'?'bg-white/10 text-white':''}`}>SYNTH</button><button onClick={()=>setPage('global')} className={`tool ${page==='global'?'bg-white/10 text-white':''}`}>GLOBAL</button></div></div>{featured.length>0&&<div className="synth-feature-grid">{(['FILTER','AMP ENV','MOD / SHAPE'] as GroupName[]).map(name=>{const group=featured.find(g=>g.name===name);if(!group)return <div key={name}/>;const visual: SynthVisualKind=name==='FILTER'?'filter':name==='AMP ENV'?'adsr':'lfo';return <ControlGroup featured key={name} name={name} descriptors={group.items} state={state} session={session} visual={visual}/>;})}</div>}<div className="synth-rack-grid">{rest.map(group=><ControlGroup key={group.name} name={group.name} descriptors={group.items} state={state} session={session}/>)}</div></section>;
}
function ControlGroup({name,descriptors,state,session,visual,featured=false}:{name:string;descriptors:ParameterDescriptor[];state:SessionState;session:SloopDeviceSession;visual?:SynthVisualKind;featured?:boolean}){const scope=descriptors[0]?.scope??0;return <section className={`synth-module ${featured?'synth-module-featured':''}`}><div className="synth-module-title">{name}</div>{visual&&<SynthVisualizer state={state} kind={visual}/>}<div className="synth-control-row">{descriptors.map(d=><ParameterControl compact key={`${d.scope}:${d.id}`} descriptor={d} value={state.values[`${d.scope}:${d.id}`]??d.defaultValue} onChange={value=>void session.setParameter(scope,d.id,value)}/>)}</div></section>}
function groupDescriptors(items:ParameterDescriptor[],global:boolean){const map=new Map<GroupName,ParameterDescriptor[]>();for(const d of items){const label=d.label.toUpperCase();let name:GroupName=global?'GLOBAL':'OSC / SOURCE';if(/FLT|FILTER|CUT|RES|TONE/.test(label))name='FILTER';else if(/ATK|ATTACK|DEC|SUS|REL|AMP/.test(label))name='AMP ENV';else if(/LFO|PIT|PHS|WAVE|RATE|FADE|SHP|MOD|GLIDE|GLD/.test(label))name='MOD / SHAPE';else if(/FX|DST|CHO|DLY|REV|SEND|DUST|DUCK|ROLL/.test(label))name='FX / SPACE';else if(/PAN|LEVEL|LVL|MUTE|SWING|BPM|MASTER/.test(label))name=global?'GLOBAL':'PERFORMANCE';const list=map.get(name)??[];list.push(d);map.set(name,list);}const order:GroupName[]=['OSC / SOURCE','FILTER','AMP ENV','MOD / SHAPE','FX / SPACE','PERFORMANCE','GLOBAL'];return order.filter(n=>map.has(n)).map(name=>({name,items:map.get(name)!}));}
