import { useMemo, useRef, useState } from 'react';
import type { SessionState, SloopDeviceSession, StepData } from '../../core/SloopDeviceSession';

const ROW_H=22,CELL_W=46,MIN_NOTE=36,MAX_NOTE=84;
type NoteBlock={note:number;start:number;length:number;velocity:number;level:number;ratchet:number;flags:number};
type Props={state:SessionState;session:SloopDeviceSession;first:number;visible:number;playhead:number};
const keyOf=(block:Pick<NoteBlock,'note'|'start'>)=>`${block.note}:${block.start}`;

export function EditablePianoRoll({state,session,first,visible,playhead}:Props){
 const[selectedKeys,setSelectedKeys]=useState<Set<string>>(new Set()),[message,setMessage]=useState(''),[clipboard,setClipboard]=useState<NoteBlock[]>([]),[pasteAt,setPasteAt]=useState(first);
 const blocks=useMemo(()=>buildBlocks(state.steps,first,visible),[state.steps,first,visible]);
 const selectedBlocks=useMemo(()=>blocks.filter(b=>selectedKeys.has(keyOf(b))),[blocks,selectedKeys]);
 const selected=selectedBlocks.length===1?selectedBlocks[0]:null;
 const width=visible*CELL_W,height=(MAX_NOTE-MIN_NOTE+1)*ROW_H,maxSteps=state.info?.stepCount??64;
 function selectBlock(block:NoteBlock,additive=false){setSelectedKeys(current=>{if(!additive)return new Set([keyOf(block)]);const next=new Set(current),key=keyOf(block);if(next.has(key))next.delete(key);else next.add(key);return next;});setMessage(`${noteName(block.note)} · step ${block.start+1} · ${block.length} step${block.length===1?'':'s'}`);}
 async function addAt(step:number,note:number){const current=state.steps.find(s=>s.index===step)??emptyStep(step);if(current.notes.includes(note)||current.notes.length>=4)return;await session.setStep({...current,notes:[...current.notes,note],time:0});setSelectedKeys(new Set([`${note}:${step}`]));setMessage(`${noteName(note)} inserted at step ${step+1}`);}
 async function replaceBlock(block:NoteBlock,next:{note:number;start:number;length:number}){
  const note=Math.max(0,Math.min(127,next.note)),start=Math.max(0,Math.min(maxSteps-1,next.start)),length=Math.max(1,Math.min(next.length,maxSteps-start));
  const touched=new Map<number,StepData>();const get=(index:number)=>{let step=touched.get(index);if(!step){const src=state.steps.find(s=>s.index===index)??emptyStep(index);step={...src,notes:[...src.notes]};touched.set(index,step);}return step;};
  for(let i=0;i<block.length;i++){const index=block.start+i,step=get(index);step.notes=step.notes.filter(n=>n!==block.note);if(!step.notes.length)step.time=2;}
  for(let i=0;i<length;i++){const index=start+i,step=get(index);if(!step.notes.includes(note))step.notes=[...step.notes,note].slice(0,4);step.time=i===0?0:1;if(i===0){step.velocity=block.velocity;step.level=block.level;step.ratchet=block.ratchet;step.flags=block.flags;}}
  await session.applySteps([...touched.values()].sort((a,b)=>a.index-b.index));setSelectedKeys(new Set([`${note}:${start}`]));setMessage(`${noteName(note)} · step ${start+1} · ${length} step${length===1?'':'s'}`);
 }
 async function patchEffects(patch:Partial<Pick<NoteBlock,'velocity'|'level'|'ratchet'|'flags'>>){if(!selected)return;const firstStep=state.steps.find(s=>s.index===selected.start)??emptyStep(selected.start),next={...selected,...patch};await session.setStep({...firstStep,velocity:next.velocity,level:next.level,ratchet:next.ratchet,flags:next.flags});setMessage(`${noteName(next.note)} effects updated`);}
 function copySelection(){if(!selectedBlocks.length)return;const min=Math.min(...selectedBlocks.map(b=>b.start));setClipboard(selectedBlocks.map(b=>({...b,start:b.start-min})));setPasteAt(Math.min(maxSteps-1,min+selectionSpan(selectedBlocks)));setMessage(`${selectedBlocks.length} note${selectedBlocks.length===1?'':'s'} copied`);}
 async function pasteSelection(anchor=pasteAt){if(!clipboard.length)return;const created=clipboard.map(b=>({...b,start:anchor+b.start})).filter(b=>b.start<maxSteps).map(b=>({...b,length:Math.min(b.length,maxSteps-b.start)}));await writeBlocks(state.steps,session,[],created);setSelectedKeys(new Set(created.map(keyOf)));setMessage(`${created.length} note${created.length===1?'':'s'} pasted at step ${anchor+1}`);}
 async function duplicateSelection(){if(!selectedBlocks.length)return;const min=Math.min(...selectedBlocks.map(b=>b.start)),offset=selectionSpan(selectedBlocks),copies=selectedBlocks.map(b=>({...b,start:b.start-min+min+offset})).filter(b=>b.start<maxSteps).map(b=>({...b,length:Math.min(b.length,maxSteps-b.start)}));await writeBlocks(state.steps,session,[],copies);setSelectedKeys(new Set(copies.map(keyOf)));setMessage(`${copies.length} note${copies.length===1?'':'s'} duplicated`);}
 async function deleteSelection(){if(!selectedBlocks.length)return;await writeBlocks(state.steps,session,selectedBlocks,[]);setSelectedKeys(new Set());setMessage(`${selectedBlocks.length} note${selectedBlocks.length===1?'':'s'} deleted`);}
 return <div className="piano-editor-shell">
  <div className="piano-editor-toolbar"><div><b>PIANO ROLL</b><span> drag/resize · wheel transpose · Ctrl/Cmd/Shift-click multi-select</span></div><div className="flex flex-wrap items-center gap-1"><span className="text-[9px] text-zinc-500">{selectedBlocks.length?`${selectedBlocks.length} selected`:message}</span><button className="tool" disabled={!selectedBlocks.length} onClick={copySelection}>COPY</button><label className="field flex items-center gap-1">PASTE AT<input className="input w-14" type="number" min={1} max={maxSteps} value={pasteAt+1} onChange={e=>setPasteAt(Math.max(0,Math.min(maxSteps-1,Number(e.target.value)-1)))}/></label><button className="tool" disabled={!clipboard.length} onClick={()=>void pasteSelection()}>PASTE</button><button className="tool" disabled={!selectedBlocks.length} onClick={()=>void duplicateSelection()}>DUPLICATE</button><button className="tool text-rose-300" disabled={!selectedBlocks.length} onClick={()=>void deleteSelection()}>DELETE</button></div></div>
  <div className="piano-editor-scroll"><div className="piano-editor-ruler" style={{width:width+58}}><span/>{Array.from({length:visible},(_,i)=><b key={i}>{first+i+1}</b>)}</div><div className="piano-editor-body" style={{width:width+58,height}}>
   <div className="piano-keys" style={{height}}>{Array.from({length:MAX_NOTE-MIN_NOTE+1},(_,row)=>{const note=MAX_NOTE-row;return <button key={note} className={`piano-key ${isBlack(note)?'black':''}`} style={{top:row*ROW_H,height:ROW_H}}>{noteName(note)}</button>;})}</div>
   <div className="piano-grid" style={{left:58,width,height}} onPointerDown={e=>{if(e.currentTarget===e.target)setSelectedKeys(new Set());}}>{Array.from({length:MAX_NOTE-MIN_NOTE+1},(_,row)=>{const note=MAX_NOTE-row;return Array.from({length:visible},(_,col)=>{const step=first+col;return <button key={`${note}:${step}`} className={`piano-grid-cell ${isBlack(note)?'black':''} ${playhead===step?'playhead':''}`} style={{left:col*CELL_W,top:row*ROW_H,width:CELL_W,height:ROW_H}} onDoubleClick={()=>void addAt(step,note)} aria-label={`Insert ${noteName(note)} at step ${step+1}`}/>;});})}{blocks.map(block=><PianoNoteBlock key={keyOf(block)} block={block} first={first} selected={selectedKeys.has(keyOf(block))} onSelect={additive=>selectBlock(block,additive)} onChange={next=>void replaceBlock(block,next)}/>)}</div>
  </div></div>
  {selected&&<div className="piano-note-inspector"><div><div className="field">NOTE</div><b>{noteName(selected.note)}</b><span> · step {selected.start+1} · length {selected.length}</span></div><label className="field">VELOCITY {selected.velocity}<input type="range" min={1} max={127} value={selected.velocity} onChange={e=>void patchEffects({velocity:Number(e.target.value)})}/></label><label className="field">LEVEL {selected.level}<input type="range" min={0} max={255} value={selected.level} onChange={e=>void patchEffects({level:Number(e.target.value)})}/></label><label className="field">RATCHET<select className="select" value={selected.ratchet} onChange={e=>void patchEffects({ratchet:Number(e.target.value)})}><option value={0}>Off</option><option value={1}>2×</option><option value={2}>3×</option><option value={3}>4×</option></select></label><button className={`tool ${selected.flags&1?'text-amber-200':''}`} onClick={()=>void patchEffects({flags:selected.flags^1})}>ACCENT</button><button className={`tool ${selected.flags&2?'text-cyan-200':''}`} onClick={()=>void patchEffects({flags:selected.flags^2})}>SLIDE</button><button className="tool" onClick={()=>void replaceBlock(selected,{note:selected.note-12,start:selected.start,length:selected.length})}>-OCT</button><button className="tool" onClick={()=>void replaceBlock(selected,{note:selected.note+12,start:selected.start,length:selected.length})}>+OCT</button><button className="tool text-rose-300" onClick={()=>void deleteSelection()}>DELETE NOTE</button></div>}
  {selectedBlocks.length>1&&<div className="piano-note-inspector"><b>{selectedBlocks.length} NOTES SELECTED</b><span className="text-[9px] text-zinc-500">Copy, paste, duplicate or delete them as a group from the toolbar.</span></div>}
 </div>;
}

function PianoNoteBlock({block,first,selected,onSelect,onChange}:{block:NoteBlock;first:number;selected:boolean;onSelect:(additive:boolean)=>void;onChange:(next:{note:number;start:number;length:number})=>void}){const drag=useRef<{mode:'move'|'left'|'right';x:number;y:number}|null>(null);const row=MAX_NOTE-block.note,left=(block.start-first)*CELL_W,top=row*ROW_H;
 function begin(mode:'move'|'left'|'right',e:React.PointerEvent){e.preventDefault();e.stopPropagation();onSelect(e.ctrlKey||e.metaKey||e.shiftKey);drag.current={mode,x:e.clientX,y:e.clientY};e.currentTarget.setPointerCapture(e.pointerId);}
 function end(e:React.PointerEvent){const d=drag.current;if(!d)return;drag.current=null;const dx=Math.round((e.clientX-d.x)/CELL_W),dy=Math.round((d.y-e.clientY)/ROW_H);if(dx===0&&dy===0)return;if(d.mode==='move')onChange({note:block.note+dy,start:block.start+dx,length:block.length});else if(d.mode==='left'){const shift=Math.max(-(block.start),Math.min(block.length-1,dx));onChange({note:block.note,start:block.start+shift,length:block.length-shift});}else onChange({note:block.note,start:block.start,length:Math.max(1,block.length+dx)});}
 function wheel(e:React.WheelEvent){e.preventDefault();e.stopPropagation();const semitones=(e.shiftKey?12:1)*(e.deltaY>0?-1:1);onChange({note:block.note+semitones,start:block.start,length:block.length});}
 return <div className={`piano-note-block ${selected?'selected':''}`} style={{left,top,width:Math.max(14,block.length*CELL_W-2),height:ROW_H-2}} onPointerDown={e=>begin('move',e)} onPointerUp={end} onWheel={wheel}><i className="resize left" onPointerDown={e=>begin('left',e)} onPointerUp={end}/><span>{noteName(block.note)}<small>{block.length>1?` ×${block.length}`:''}</small></span><i className="resize right" onPointerDown={e=>begin('right',e)} onPointerUp={end}/></div>;
}
async function writeBlocks(steps:StepData[],session:SloopDeviceSession,remove:NoteBlock[],add:NoteBlock[]){const touched=new Map<number,StepData>();const get=(index:number)=>{let step=touched.get(index);if(!step){const src=steps.find(s=>s.index===index)??emptyStep(index);step={...src,notes:[...src.notes]};touched.set(index,step);}return step;};for(const block of remove)for(let i=0;i<block.length;i++){const step=get(block.start+i);step.notes=step.notes.filter(n=>n!==block.note);if(!step.notes.length)step.time=2;}for(const block of add)for(let i=0;i<block.length;i++){const step=get(block.start+i);if(!step.notes.includes(block.note))step.notes=[...step.notes,block.note].slice(0,4);step.time=i===0?0:1;if(i===0){step.velocity=block.velocity;step.level=block.level;step.ratchet=block.ratchet;step.flags=block.flags;}}if(touched.size)await session.applySteps([...touched.values()].sort((a,b)=>a.index-b.index));}
function selectionSpan(blocks:NoteBlock[]){if(!blocks.length)return 1;const min=Math.min(...blocks.map(b=>b.start)),max=Math.max(...blocks.map(b=>b.start+b.length));return Math.max(1,max-min);}
function buildBlocks(steps:StepData[],first:number,visible:number){const out:NoteBlock[]=[];const end=first+visible;for(let note=MIN_NOTE;note<=MAX_NOTE;note++){let i=first;while(i<end){const s=steps.find(x=>x.index===i);if(!s?.notes.includes(note)){i++;continue;}const start=i,velocity=s.velocity,level=s.level,ratchet=s.ratchet,flags=s.flags;i++;while(i<end){const next=steps.find(x=>x.index===i);if(!next?.notes.includes(note)||next.time!==1)break;i++;}out.push({note,start,length:i-start,velocity,level,ratchet,flags});}}return out;}
function emptyStep(index:number):StepData{return{index,notes:[],time:2,flags:0,velocity:100,level:100,ratchet:0};}
function noteName(note:number){const names=['C','C#','D','D#','E','F','F#','G','G#','A','A#','B'];return`${names[(note%12+12)%12]}${Math.floor(note/12)-1}`;}
function isBlack(note:number){return[1,3,6,8,10].includes((note%12+12)%12);}
