import { useEffect, useRef, useState } from 'react';
import { Download, FolderOpen, Save, Trash2, Upload } from 'lucide-react';
import { readCString, SloopCommand } from '../../protocol/sloopProtocol';
import type { ProjectSlot, SessionState, SloopDeviceSession, UserPresetSummary } from '../../core/SloopDeviceSession';
import { captureStudioProject, parseProjectFile, restoreStudioProject } from '../../features/projects/projectFile';

export function LibraryPanel({state,session}:{state:SessionState;session:SloopDeviceSession}){
 const[projects,setProjects]=useState<ProjectSlot[]>([]),[presets,setPresets]=useState<UserPresetSummary[]>([]),[factory,setFactory]=useState<string[]>([]),[message,setMessage]=useState('');const track=state.tracks[state.selectedTrack],restoreInput=useRef<HTMLInputElement>(null);
 async function refresh(){try{const[p,u]=await Promise.all([session.queryProjects(),session.listUserPresets()]);setProjects(p);setPresets(u);if(track&&state.selectedTrack<3){const r=await session.request(SloopCommand.Names,[track.engine]);let offset=1;const count=r.data[offset++]??0,names:string[]=[];for(let i=0;i<count;i++){const s=readCString(r.data,offset);names.push(s.value);offset=s.next;}setFactory(names);}else setFactory([]);}catch(e){setMessage(e instanceof Error?e.message:'Unable to load library');}}
 useEffect(()=>{void refresh();},[state.selectedTrack,track?.engine]);
 useEffect(()=>{const save=()=>void exportProject(),open=()=>restoreInput.current?.click();window.addEventListener('sloopui:save-project',save);window.addEventListener('sloopui:open-project',open);return()=>{window.removeEventListener('sloopui:save-project',save);window.removeEventListener('sloopui:open-project',open);};},[session]);
 async function act(label:string,fn:()=>Promise<unknown>){setMessage(`${label}…`);try{await fn();setMessage(`${label} done`);await refresh();}catch(e){setMessage(e instanceof Error?e.message:`${label} failed`);}}
 async function exportProject(){setMessage('Capturing all tracks…');try{const file=await captureStudioProject(session);download('sloop-project.sloop.json',JSON.stringify(file,null,2));setMessage('Project file exported');}catch(e){setMessage(e instanceof Error?e.message:'Export failed');}}
 async function importProject(file:File){setMessage('Restoring project…');try{const parsed=parseProjectFile(await file.text());await restoreStudioProject(session,parsed,setMessage);await refresh();}catch(e){setMessage(e instanceof Error?e.message:'Restore failed');}}
 return <section className="hardware-panel rounded-xl p-4" id="library"><div className="mb-3 flex flex-wrap items-center justify-between gap-2"><div><b>Projects & Presets</b><span className="ml-2 text-xs text-zinc-500">device flash + portable studio files</span></div><div className="flex items-center gap-1"><button onClick={()=>void exportProject()} className="tool"><Download size={11} className="mr-1"/>PROJECT JSON</button><label className="tool cursor-pointer"><Upload size={11} className="mr-1"/>RESTORE<input ref={restoreInput} type="file" accept="application/json,.json" className="hidden" onChange={e=>{const f=e.target.files?.[0];if(f)void importProject(f);e.currentTarget.value='';}}/></label><span className="ml-2 text-[10px] text-zinc-500">{message}</span></div></div>
  <div className="grid gap-4 xl:grid-cols-[1fr_1.4fr_1fr]"><div><div className="mb-2 text-[10px] font-black uppercase tracking-widest text-zinc-500">Projects A–D</div><div className="space-y-1">{projects.map(project=><div key={project.slot} className="flex items-center gap-1 rounded border border-white/8 bg-black/20 p-2"><b className="mr-auto text-xs">{String.fromCharCode(65+project.slot)} · {project.used?'used':'empty'}</b><button title="Load" disabled={!project.used} onClick={()=>void act('Load project',()=>session.project(0,project.slot))} className="rounded border border-white/10 p-1.5 disabled:opacity-30"><FolderOpen size={13}/></button><button title="Save" onClick={()=>void act('Save project',()=>session.project(1,project.slot))} className="rounded border border-white/10 p-1.5"><Save size={13}/></button></div>)}</div></div>
   <div><div className="mb-2 text-[10px] font-black uppercase tracking-widest text-zinc-500">User presets U01–U32</div><div className="grid max-h-64 grid-cols-2 gap-1 overflow-auto pr-1">{presets.map(p=><div key={p.slot} className="rounded border border-white/8 bg-black/20 p-2"><div className="truncate text-[10px]"><b>U{String(p.slot+1).padStart(2,'0')}</b> <span className="text-zinc-500">{p.used?p.name:'empty'}</span></div><div className="mt-1 flex gap-1"><button disabled={!p.used} onClick={()=>void act('Load preset',()=>session.loadUserPreset(p.slot))} className="tool py-1 text-[9px] disabled:opacity-30">LOAD</button><button onClick={()=>{const name=window.prompt('Preset name (max 12 ASCII characters)','');if(name!==null)void act('Store preset',()=>session.storeUserPreset(p.slot,name));}} className="tool py-1 text-[9px]">STORE</button><button disabled={!p.used} onClick={()=>void act('Erase preset',()=>session.eraseUserPreset(p.slot))} className="ml-auto rounded border border-white/10 p-1 disabled:opacity-30"><Trash2 size={10}/></button></div></div>)}</div></div>
   <div><div className="mb-2 text-[10px] font-black uppercase tracking-widest text-zinc-500">Factory presets</div>{state.selectedTrack===3?<div className="text-xs text-zinc-600">Drum track uses kits rather than synth presets.</div>:<div className="max-h-64 space-y-1 overflow-auto">{factory.map((name,index)=><button key={index} onClick={()=>track&&void act('Apply factory preset',()=>session.applyFactoryPreset(track.engine,index))} className="block w-full rounded border border-white/7 bg-black/20 px-2 py-1.5 text-left text-[10px] hover:bg-white/5"><span className="mr-2 font-mono text-zinc-600">{String(index+1).padStart(2,'0')}</span>{name}</button>)}</div>}</div></div>
 </section>;
}
function download(name:string,text:string){const url=URL.createObjectURL(new Blob([text],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
