import { useEffect, useRef, useState } from 'react';
import type { ParameterDescriptor } from '../../core/SloopDeviceSession';

export function formatParameterValue(d:ParameterDescriptor,v:number){if(d.format===11)return v?'ON':'OFF';if(d.format===8&&d.enumValues[v-d.min])return d.enumValues[v-d.min];if(d.format===14)return`${50+Math.round(v/4)}%`;if(d.format===15)return v===0?'OFF':v<0?`LP ${Math.round(-v*100/64)}%`:`HP ${Math.round(v*100/63)}%`;if(d.format===2)return`${v>0?'+':''}${Math.round(v*100/64)}%`;if(d.format===6)return v<=0?'OFF':`${((v-112)/2).toFixed(1)} dB`;if(d.format===9)return`${v} BPM`;return`${v}${d.unit?` ${d.unit}`:''}`;}
export function ParameterControl({descriptor,value,onChange,compact=false}:{descriptor:ParameterDescriptor;value:number;onChange:(value:number)=>void;compact?:boolean}){
 const[draft,setDraft]=useState(value),timer=useRef<number|null>(null),drag=useRef<{y:number;value:number}|null>(null);useEffect(()=>setDraft(value),[value]);useEffect(()=>()=>{if(timer.current)clearTimeout(timer.current);},[]);
 const percent=descriptor.max===descriptor.min?0:(draft-descriptor.min)/(descriptor.max-descriptor.min),normalized=Math.max(0,Math.min(1,percent)),angle=-135+normalized*270,ledCount=21,active=Math.round(normalized*(ledCount-1));
 function commit(next:number,immediate=false){const v=Math.max(descriptor.min,Math.min(descriptor.max,Math.round(next)));setDraft(v);if(timer.current)clearTimeout(timer.current);if(immediate)onChange(v);else timer.current=window.setTimeout(()=>onChange(v),20);}
 function reset(){commit(descriptor.defaultValue,true);}function key(event:React.KeyboardEvent){if(!['ArrowLeft','ArrowDown','ArrowRight','ArrowUp','Home'].includes(event.key))return;event.preventDefault();if(event.key==='Home')return reset();const direction=event.key==='ArrowLeft'||event.key==='ArrowDown'?-1:1;commit(draft+direction*(event.shiftKey?10:1),true);}
 const knob=<div className={`knob-shell ${compact?'knob-shell-sm':''}`}><div className="knob-led-bed"/>{Array.from({length:ledCount},(_,i)=>{const a=-135+i*(270/(ledCount-1));return <span key={i} className={`knob-led ${i<=active?'knob-led-active':''}`} style={{transform:`rotate(${a}deg) translateY(-50%)`}}/>;})}<button aria-label={`${descriptor.label}: ${formatParameterValue(descriptor,draft)}`} title="Drag vertically · arrows fine · Shift ×10 · double click reset" onDoubleClick={reset} onKeyDown={key} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);drag.current={y:e.clientY,value:draft};}} onPointerMove={e=>{if(!drag.current)return;const range=descriptor.max-descriptor.min,sensitivity=range/150;commit(drag.current.value+(drag.current.y-e.clientY)*sensitivity);}} onPointerUp={()=>{drag.current=null;commit(draft,true);}} className="knob-3d"><span className="knob-cap"/><span className="knob-highlight"/><span className="knob-pointer" style={{transform:`translateX(-50%) rotate(${angle}deg)`}}/><span className="knob-center"/></button></div>;
 if(descriptor.format===11)return <div className="synth-control"><div className="synth-label">{descriptor.label}</div><button onClick={()=>commit(draft?0:1,true)} className={`hardware-toggle ${draft?'hardware-toggle-on':''}`}><span/>{draft?'ON':'OFF'}</button></div>;
 if(descriptor.format===8&&descriptor.enumValues.length>0)return <div className="synth-control"><div className="synth-label">{descriptor.label}</div>{knob}<select aria-label={descriptor.label} value={draft} onChange={e=>commit(Number(e.target.value),true)} className="knob-select">{descriptor.enumValues.map((name,index)=><option className="bg-zinc-900" key={index} value={descriptor.min+index}>{name}</option>)}</select></div>;
 return <div className="synth-control"><div className="synth-label">{descriptor.label}</div>{knob}<div className="knob-readout">{formatParameterValue(descriptor,draft)}</div></div>;
}
