import { useEffect, useRef, useState } from 'react';
import type { ParameterDescriptor } from '../../core/SloopDeviceSession';

export function formatParameterValue(d:ParameterDescriptor,v:number){if(d.format===11)return v?'ON':'OFF';if(d.format===8&&d.enumValues[v-d.min])return d.enumValues[v-d.min];if(d.format===14)return`${50+Math.round(v/4)}%`;if(d.format===15)return v===0?'OFF':v<0?`LP ${Math.round(-v*100/64)}%`:`HP ${Math.round(v*100/63)}%`;if(d.format===2)return`${v>0?'+':''}${Math.round(v*100/64)}%`;if(d.format===6)return v<=0?'OFF':`${((v-112)/2).toFixed(1)} dB`;if(d.format===9)return`${v} BPM`;return`${v}${d.unit?` ${d.unit}`:''}`;}
export function ParameterControl({descriptor,value,onChange}:{descriptor:ParameterDescriptor;value:number;onChange:(value:number)=>void}){
 const[draft,setDraft]=useState(value),timer=useRef<number|null>(null);useEffect(()=>setDraft(value),[value]);useEffect(()=>()=>{if(timer.current)clearTimeout(timer.current);},[]);
 const percent=descriptor.max===descriptor.min?0:(draft-descriptor.min)/(descriptor.max-descriptor.min),angle=-135+Math.max(0,Math.min(1,percent))*270;
 function commit(next:number,immediate=false){const v=Math.max(descriptor.min,Math.min(descriptor.max,Math.round(next)));setDraft(v);if(timer.current)clearTimeout(timer.current);if(immediate)onChange(v);else timer.current=window.setTimeout(()=>onChange(v),32);}
 function reset(){commit(descriptor.defaultValue,true);}
 function key(event:React.KeyboardEvent){if(!['ArrowLeft','ArrowDown','ArrowRight','ArrowUp','Home'].includes(event.key))return;event.preventDefault();if(event.key==='Home')return reset();const direction=event.key==='ArrowLeft'||event.key==='ArrowDown'?-1:1;commit(draft+direction*(event.shiftKey?10:1),true);}
 return <div className="rounded-lg border border-white/8 bg-black/20 p-3" onDoubleClick={reset} onKeyDown={key}><div className="mb-2 flex items-center justify-between gap-2"><span className="truncate text-[10px] font-black tracking-[.14em] text-zinc-500" title={`${descriptor.label} · double-click reset`}>{descriptor.label}</span><span className="whitespace-nowrap font-mono text-[11px] text-emerald-200">{formatParameterValue(descriptor,draft)}</span></div><div className="flex items-center gap-3"><div className="knob relative h-11 w-11 shrink-0 rounded-full"><span className="absolute left-1/2 top-1 h-4 w-0.5 origin-[50%_18px] -translate-x-1/2 rounded bg-white/80" style={{transform:`translateX(-50%) rotate(${angle}deg)`}}/></div>{descriptor.format===8&&descriptor.enumValues.length>0?<select value={draft} onChange={e=>commit(Number(e.target.value),true)} className="select min-w-0 flex-1">{descriptor.enumValues.map((name,index)=><option key={index} value={descriptor.min+index}>{name}</option>)}</select>:descriptor.format===11?<button onClick={()=>commit(draft?0:1,true)} className={`flex-1 rounded border px-2 py-1.5 text-xs font-bold ${draft?'border-emerald-300/50 bg-emerald-300/15 text-emerald-100':'border-white/10 text-zinc-500'}`}>{draft?'ON':'OFF'}</button>:<input aria-label={descriptor.label} className="w-full" type="range" min={descriptor.min} max={descriptor.max} step={1} value={draft} onChange={e=>commit(Number(e.target.value))} onPointerUp={()=>commit(draft,true)}/>}</div><div className="mt-1 text-[8px] text-zinc-700">arrows fine · Shift ×10 · Home/double-click reset</div></div>;
}
