import { useEffect, useMemo, useRef, useState, type ReactNode } from 'react';
import { Columns2, Rows2, ArrowLeftRight, RotateCcw } from 'lucide-react';

type Layout={vertical:boolean;swapped:boolean;ratio:number};
export function ResizableDock({left,right,label='Workspace'}:{left:ReactNode;right:ReactNode;label?:string}){
 const key=useMemo(()=>`sloopui.dock.${label.toLowerCase().replace(/\W+/g,'-')}`,[label]);
 const initial=useMemo<Layout>(()=>{try{return{vertical:false,swapped:false,ratio:55,...JSON.parse(localStorage.getItem(key)||'{}')}}catch{return{vertical:false,swapped:false,ratio:55}}},[key]);
 const[vertical,setVertical]=useState(initial.vertical),[swapped,setSwapped]=useState(initial.swapped),[ratio,setRatio]=useState(initial.ratio);const ref=useRef<HTMLDivElement>(null);
 useEffect(()=>{localStorage.setItem(key,JSON.stringify({vertical,swapped,ratio}));},[key,vertical,swapped,ratio]);
 function resize(client:number){const el=ref.current;if(!el)return;const rect=el.getBoundingClientRect(),value=vertical?(client-rect.top)/rect.height:(client-rect.left)/rect.width;setRatio(Math.max(25,Math.min(75,Math.round(value*100))));}
 function reset(){setVertical(false);setSwapped(false);setRatio(55);localStorage.removeItem(key);}
 const first=swapped?right:left,second=swapped?left:right;
 return <section><div className="mb-2 flex items-center justify-end gap-1 text-[9px] text-zinc-600"><span className="mr-auto uppercase tracking-widest">{label}</span><button className="tool" aria-label="Swap docked regions" onClick={()=>setSwapped(v=>!v)}><ArrowLeftRight size={10}/>Swap</button><button className="tool" aria-label="Toggle dock orientation" onClick={()=>setVertical(v=>!v)}>{vertical?<Columns2 size={10}/>:<Rows2 size={10}/>}Dock</button><button className="tool" aria-label="Reset dock layout" onClick={reset}><RotateCcw size={10}/>Reset</button></div><div ref={ref} className={`studio-dock ${vertical?'studio-dock-vertical':''}`} style={vertical?{gridTemplateRows:`${ratio}% 6px ${100-ratio}%`}:{gridTemplateColumns:`${ratio}% 6px ${100-ratio}%`}}><div className="min-w-0 min-h-0">{first}</div><div role="separator" aria-orientation={vertical?'horizontal':'vertical'} tabIndex={0} className="studio-splitter" onPointerDown={event=>{event.currentTarget.setPointerCapture(event.pointerId);const move=(e:PointerEvent)=>resize(vertical?e.clientY:e.clientX);const up=()=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up);};window.addEventListener('pointermove',move);window.addEventListener('pointerup',up);}} onKeyDown={e=>{if((!vertical&&e.key==='ArrowLeft')||(vertical&&e.key==='ArrowUp'))setRatio(r=>Math.max(25,r-5));if((!vertical&&e.key==='ArrowRight')||(vertical&&e.key==='ArrowDown'))setRatio(r=>Math.min(75,r+5));}}/><div className="min-w-0 min-h-0">{second}</div></div></section>;
}
