import { Download, Pause, Play, RefreshCw, RotateCcw, Square, Undo2, Upload } from 'lucide-react';
import { useRef, useState } from 'react';
import type { DrumStepData, SessionState, SloopDeviceSession, StepData } from '../../core/SloopDeviceSession';
import { exportSequenceJson, humanizeSteps, importSequenceJson, quantizeVelocity, reverseDrums, reverseSteps, rotateDrums, rotateSteps, sequenceToMidi } from '../../features/sequencer/sequenceTools';

export function Sequencer({state,session,virtual,playing,playhead,onTogglePlay,onAudition}:{state:SessionState;session:SloopDeviceSession;virtual:boolean;playing:boolean;playhead:number;onTogglePlay:()=>void;onAudition:(note:number)=>void}){
 const count=state.info?.stepCount??64,isDrums=state.selectedTrack===3; const [view,setView]=useState<'steps'|'piano'>('steps'); const [progress,setProgress]=useState(''); const undoRef=useRef<Array<{synth:StepData[];drums:DrumStepData[]}>>([]);
 const bpmDescriptor=state.descriptors.find(d=>d.scope===1&&d.label.toUpperCase()==='BPM'); const bpm=bpmDescriptor?state.values[`1:${bpmDescriptor.id}`]??120:120;
 function saveUndo(){undoRef.current.push({synth:state.steps.map(s=>({...s,notes:[...s.notes]})),drums:state.drumSteps.map(s=>({...s,on:[...s.on],levels:[...s.levels],ratchets:[...s.ratchets]}))});if(undoRef.current.length>20)undoRef.current.shift();}
 async function transform(kind:'rotateL'|'rotateR'|'reverse'|'humanize'|'quantize') {saveUndo();setProgress('Applying…');try{if(isDrums){let next=state.drumSteps;if(kind==='rotateL')next=rotateDrums(next,-1,count);if(kind==='rotateR')next=rotateDrums(next,1,count);if(kind==='reverse')next=reverseDrums(next,count);await session.applyDrumSteps(next);}else{let next=state.steps;if(kind==='rotateL')next=rotateSteps(next,-1,count);if(kind==='rotateR')next=rotateSteps(next,1,count);if(kind==='reverse')next=reverseSteps(next,count);if(kind==='humanize')next=humanizeSteps(next,8);if(kind==='quantize')next=quantizeVelocity(next,.75,100);await session.applySteps(next);}setProgress('Done');}catch(e){setProgress(e instanceof Error?e.message:'Failed');}}
 async function undo(){const previous=undoRef.current.pop();if(!previous)return;setProgress('Undo…');if(isDrums)await session.applyDrumSteps(previous.drums);else await session.applySteps(previous.synth);setProgress('Undone');}
 function download(name:string,data:BlobPart,type:string){const url=URL.createObjectURL(new Blob([data],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 async function importJson(file:File){const parsed=importSequenceJson(await file.text());saveUndo();if(isDrums&&parsed.drums.length)await session.applyDrumSteps(parsed.drums);else if(!isDrums&&parsed.synth.length)await session.applySteps(parsed.synth);}
 return <section className="hardware-panel rounded-xl p-4" id="sequence">
  <div className="mb-3 flex flex-wrap items-center justify-between gap-3"><div><b>{isDrums?'Drum Grid':'Sequence'}</b><span className="ml-2 text-xs text-zinc-500">{isDrums?`16 lanes × ${count} steps`:`${count} steps · 4-note chords · transforms · MIDI/JSON`}</span></div><div className="flex flex-wrap gap-1">
   {!isDrums&&<><button onClick={()=>setView('steps')} className={`rounded border px-2 py-1 text-[10px] ${view==='steps'?'border-emerald-300/50 text-emerald-200':'border-white/10 text-zinc-500'}`}>STEP</button><button onClick={()=>setView('piano')} className={`rounded border px-2 py-1 text-[10px] ${view==='piano'?'border-emerald-300/50 text-emerald-200':'border-white/10 text-zinc-500'}`}>PIANO</button></>}
   {virtual?<button onClick={onTogglePlay} className={`rounded px-3 py-1.5 text-xs font-black ${playing?'bg-amber-300 text-black':'bg-emerald-300 text-black'}`}>{playing?<><Pause size={12} className="mr-1 inline"/>PAUSE</>:<><Play size={12} className="mr-1 inline"/>PLAY</>}</button>:<div className="rounded border border-white/8 px-2.5 py-1.5 text-[10px] text-zinc-500"><Square size={11} className="mr-1 inline"/>transport on FM-1</div>}
   <button onClick={()=>void session.refreshSequence()} className="rounded border border-white/10 px-2 py-1.5 text-xs"><RefreshCw size={12}/></button>
  </div></div>
  <div className="mb-3 flex flex-wrap gap-1 rounded-lg border border-white/7 bg-black/20 p-2"><button onClick={()=>void transform('rotateL')} className="tool">← Rotate</button><button onClick={()=>void transform('rotateR')} className="tool">Rotate →</button><button onClick={()=>void transform('reverse')} className="tool"><RotateCcw size={11} className="mr-1 inline"/>Reverse</button>{!isDrums&&<><button onClick={()=>void transform('humanize')} className="tool">Humanize</button><button onClick={()=>void transform('quantize')} className="tool">Quantize 75%</button></>}<button disabled={!undoRef.current.length} onClick={()=>void undo()} className="tool disabled:opacity-30"><Undo2 size={11} className="mr-1 inline"/>Undo</button><button onClick={()=>download('sloop-sequence.json',exportSequenceJson({synth:state.steps,drums:state.drumSteps}),'application/json')} className="tool"><Download size={11} className="mr-1 inline"/>JSON</button>{!isDrums&&<button onClick={()=>download('sloop-sequence.mid',sequenceToMidi(state.steps,bpm),'audio/midi')} className="tool">MIDI</button>}<label className="tool cursor-pointer"><Upload size={11} className="mr-1 inline"/>Import<input type="file" accept="application/json,.json" className="hidden" onChange={e=>{const f=e.target.files?.[0];if(f)void importJson(f);}}/></label><span className="ml-auto self-center text-[9px] text-zinc-600">{progress}</span></div>
  {isDrums?<DrumGrid state={state} session={session} playhead={playhead} count={count}/>:view==='piano'?<PianoRoll state={state} session={session} count={count} playhead={playhead}/>:<SynthGrid state={state} session={session} count={count} playhead={playhead} onAudition={onAudition}/>} 
 </section>;
}

function SynthGrid({state,session,count,playhead,onAudition}:{state:SessionState;session:SloopDeviceSession;count:number;playhead:number;onAudition:(note:number)=>void}){
 const [insertNote,setInsertNote]=useState(60);const [selected,setSelected]=useState<number|null>(null);const selectedStep=selected===null?undefined:state.steps.find(s=>s.index===selected);
 async function toggle(index:number){const current=state.steps.find(s=>s.index===index);if(current?.notes.length)await session.setStep({...current,notes:[],time:2});else await session.toggleStep(index,insertNote);setSelected(index);}
 async function patch(patch:Partial<StepData>){if(selected===null)return;const current=state.steps.find(s=>s.index===selected)??{index:selected,notes:[insertNote],time:0 as const,flags:0,velocity:100,level:100,ratchet:0};await session.setStep({...current,...patch});}
 return <div><div className="mb-3 flex flex-wrap items-end gap-3 rounded-lg border border-white/7 bg-black/20 p-3"><label className="field">Insert note<select value={insertNote} onChange={e=>setInsertNote(Number(e.target.value))} className="select">{notes(36,84).map(n=><option key={n} value={n}>{noteName(n)} · {n}</option>)}</select></label><button onClick={()=>onAudition(insertNote)} className="tool">Audition</button><div className="ml-auto text-[10px] text-zinc-600">Right-click: select/audition · active step inspector supports up to four chord notes</div></div>
  <div className="grid gap-2 md:grid-cols-2 xl:grid-cols-4">{Array.from({length:Math.ceil(count/16)},(_,bank)=><div key={bank} className="rounded-lg border border-white/7 bg-black/20 p-2"><div className="mb-2 text-[10px] font-bold text-zinc-600">{bank*16+1}–{Math.min(count,bank*16+16)}</div><div className="grid grid-cols-4 gap-1">{Array.from({length:16},(_,local)=>{const index=bank*16+local;if(index>=count)return null;const step=state.steps.find(s=>s.index===index),active=!!step?.notes.length;return <button key={index} onContextMenu={e=>{e.preventDefault();setSelected(index);step?.notes.forEach(onAudition);}} onClick={()=>void toggle(index)} className={`relative h-12 rounded border font-mono text-[10px] ${playhead===index?'ring-2 ring-white/80':selected===index?'ring-2 ring-cyan-300/70':''} ${active?'border-emerald-300/60 bg-emerald-300/20 text-emerald-100':'border-white/7 bg-black/20 text-zinc-600'}`}>{active?step!.notes.map(noteName).join('·'):index+1}{active&&<span className="absolute bottom-1 right-1 text-[8px] text-emerald-300/60">{step?.ratchet?`R${step.ratchet+1}`:''}</span>}</button>;})}</div></div>)}</div>
  {selected!==null&&<div className="mt-3 grid gap-3 rounded-lg border border-cyan-300/15 bg-cyan-300/[.03] p-3 md:grid-cols-2 xl:grid-cols-6"><div><div className="field">Step</div><div className="font-mono text-sm">{selected+1}</div></div><label className="field xl:col-span-2">Notes (C4 E4 G4, max 4)<input className="input" defaultValue={selectedStep?.notes.map(noteName).join(' ')??''} onBlur={e=>void patch({notes:parseNotes(e.target.value).slice(0,4),time:parseNotes(e.target.value).length?0:2})}/></label><label className="field">Velocity {selectedStep?.velocity??100}<input type="range" min={1} max={127} value={selectedStep?.velocity??100} onChange={e=>void patch({velocity:Number(e.target.value)})}/></label><label className="field">Level {selectedStep?.level??100}<input type="range" min={0} max={255} value={selectedStep?.level??100} onChange={e=>void patch({level:Number(e.target.value)})}/></label><label className="field">Ratchet<select className="select" value={selectedStep?.ratchet??0} onChange={e=>void patch({ratchet:Number(e.target.value)})}><option value={0}>Off</option><option value={1}>2×</option><option value={2}>3×</option><option value={3}>4×</option></select></label><div className="flex gap-1"><button onClick={()=>void patch({flags:(selectedStep?.flags??0)^1})} className="tool">ACC</button><button onClick={()=>void patch({flags:(selectedStep?.flags??0)^2})} className="tool">SLIDE</button></div></div>}
 </div>;
}

function PianoRoll({state,session,count,playhead}:{state:SessionState;session:SloopDeviceSession;count:number;playhead:number}){const pitches=notes(48,72).reverse();return <div className="max-h-[520px] overflow-auto rounded-lg border border-white/8 bg-black/20"><div className="min-w-[1200px]">{pitches.map(note=><div key={note} className="grid grid-cols-[52px_repeat(64,minmax(14px,1fr))] gap-px"><span className={`sticky left-0 z-10 border-r border-white/10 px-1 py-0.5 text-[8px] ${note%12===0?'bg-zinc-700':'bg-zinc-900'}`}>{noteName(note)}</span>{Array.from({length:count},(_,index)=>{const step=state.steps.find(s=>s.index===index),active=step?.notes.includes(note);return <button key={index} title={`${noteName(note)} · step ${index+1}`} onClick={()=>{const current=step??{index,notes:[],time:2 as const,flags:0,velocity:100,level:100,ratchet:0};const list=active?current.notes.filter(n=>n!==note):[...current.notes,note].slice(0,4);void session.setStep({...current,notes:list,time:list.length?0:2});}} className={`h-4 ${playhead===index?'ring-1 ring-white':''} ${active?'bg-emerald-300/70':'bg-white/[.025] hover:bg-white/10'}`}/>;})}</div>)}</div></div>;}

function DrumGrid({state,session,playhead,count}:{state:SessionState;session:SloopDeviceSession;playhead:number;count:number}){const[bank,setBank]=useState(0),[level,setLevel]=useState(2),[ratchet,setRatchet]=useState(0);const banks=Math.max(1,Math.ceil(count/16)),safe=Math.min(bank,banks-1),first=safe*16,visible=Math.min(16,count-first);return <div><div className="mb-2 flex flex-wrap items-end gap-2"><div className="flex gap-1">{Array.from({length:banks},(_,i)=><button key={i} onClick={()=>setBank(i)} className={`tool ${safe===i?'border-rose-300/50 text-rose-200':''}`}>{i*16+1}–{Math.min(count,i*16+16)}</button>)}</div><label className="field">Hit level<select className="select" value={level} onChange={e=>setLevel(Number(e.target.value))}><option value={0}>Ghost</option><option value={1}>Soft</option><option value={2}>Normal</option><option value={3}>Hard</option></select></label><label className="field">Ratchet<select className="select" value={ratchet} onChange={e=>setRatchet(Number(e.target.value))}><option value={0}>Off</option><option value={1}>2×</option><option value={2}>3×</option><option value={3}>4×</option></select></label></div><div className="overflow-auto"><div className="min-w-[1050px] space-y-1">{Array.from({length:16},(_,lane)=><div key={lane} className="grid grid-cols-[72px_repeat(16,1fr)] gap-1"><span className="py-2 text-[10px] font-bold text-zinc-500">LANE {lane+1}</span>{Array.from({length:visible},(_,local)=>{const stepIndex=first+local,step=state.drumSteps.find(s=>s.index===stepIndex),on=step?.on[lane]??false;return <button key={stepIndex} onClick={()=>void session.setDrumLane(stepIndex,lane,!on,level,ratchet)} className={`h-8 rounded border text-[9px] ${playhead===stepIndex?'ring-2 ring-white/80':''} ${on?'border-rose-300/60 bg-rose-300/25 text-rose-100':'border-white/7 bg-black/20 text-zinc-700'}`}>{stepIndex+1}{on?<span className="ml-1 opacity-60">{(step?.levels[lane]??0)+1}/{(step?.ratchets[lane]??0)+1}</span>:''}</button>;})}</div>)}</div></div></div>;}

function notes(from:number,to:number){return Array.from({length:to-from},(_,i)=>from+i);}function noteName(note:number){const names=['C','C#','D','D#','E','F','F#','G','G#','A','A#','B'];return`${names[note%12]}${Math.floor(note/12)-1}`;}
function parseNotes(value:string){const names:Record<string,number>={C:0,'C#':1,DB:1,D:2,'D#':3,EB:3,E:4,F:5,'F#':6,GB:6,G:7,'G#':8,AB:8,A:9,'A#':10,BB:10,B:11};return value.trim().split(/[ ,]+/).map(token=>{if(/^\d+$/.test(token))return Number(token);const m=/^([A-Ga-g])([#b]?)(-?\d)$/.exec(token);if(!m)return-1;const key=(m[1].toUpperCase()+(m[2]?m[2].toUpperCase():''));return(names[key]??-99)+(Number(m[3])+1)*12;}).filter(n=>n>=0&&n<=127);}
