import { Download, Pause, Play, RefreshCw, RotateCcw, Square, Undo2, Upload } from 'lucide-react';
import { useEffect, useRef, useState } from 'react';
import type { DrumStepData, SessionState, SloopDeviceSession, StepData } from '../../core/SloopDeviceSession';
import { clearRange, duplicateRange, exportSequenceJson, humanizeSteps, importSequenceJson, midiToSequence, quantizeVelocity, reverseDrums, reverseSteps, rotateDrums, rotateSteps, sequenceToMidi } from '../../features/sequencer/sequenceTools';
import { getTrackProbability, setTrackProbability } from '../../features/sequencer/sequenceRuntime';

const TRACKS=['SYNTH 1','SYNTH 2','SYNTH 3','DRUMS'];
export function Sequencer({state,session,virtual,playing,playhead,onTogglePlay,onAudition}:{state:SessionState;session:SloopDeviceSession;virtual:boolean;playing:boolean;playhead:number;onTogglePlay:()=>void;onAudition:(note:number)=>void}){
 const count=state.info?.stepCount??64,isDrums=state.selectedTrack===3,banks=Math.max(1,Math.ceil(count/16));
 const[bank,setBank]=useState(0),[view,setView]=useState<'steps'|'piano'>('steps'),[progress,setProgress]=useState(''),[insertNote,setInsertNote]=useState(60),[selected,setSelected]=useState<number|null>(null),[from,setFrom]=useState(1),[to,setTo]=useState(Math.min(16,count)),[destination,setDestination]=useState(Math.min(17,count)),[probability,setProbabilityState]=useState(Math.round(getTrackProbability(state.selectedTrack)*100)),[drumLevel,setDrumLevel]=useState(2),[drumRatchet,setDrumRatchet]=useState(0);
 const undoRef=useRef<Array<{synth:StepData[];drums:DrumStepData[]}>>([]),safeBank=Math.min(bank,banks-1),first=safeBank*16,visible=Math.min(16,count-first);
 const bpmDescriptor=state.descriptors.find(d=>d.scope===1&&d.label.toUpperCase()==='BPM'),bpm=bpmDescriptor?state.values[`1:${bpmDescriptor.id}`]??120:120;
 useEffect(()=>{setBank(0);setSelected(null);setProbabilityState(Math.round(getTrackProbability(state.selectedTrack)*100));},[state.selectedTrack]);
 useEffect(()=>{const handler=()=>void undo();window.addEventListener('sloopui:undo',handler);return()=>window.removeEventListener('sloopui:undo',handler);});
 function saveUndo(){undoRef.current.push({synth:state.steps.map(s=>({...s,notes:[...s.notes]})),drums:state.drumSteps.map(s=>({...s,on:[...s.on],levels:[...s.levels],ratchets:[...s.ratchets]}))});if(undoRef.current.length>20)undoRef.current.shift();}
 async function transform(kind:'rotateL'|'rotateR'|'reverse'|'humanize'|'quantize'){saveUndo();setProgress('Applying…');try{if(isDrums){let next=state.drumSteps;if(kind==='rotateL')next=rotateDrums(next,-1,count);if(kind==='rotateR')next=rotateDrums(next,1,count);if(kind==='reverse')next=reverseDrums(next,count);await session.applyDrumSteps(next);}else{let next=state.steps;if(kind==='rotateL')next=rotateSteps(next,-1,count);if(kind==='rotateR')next=rotateSteps(next,1,count);if(kind==='reverse')next=reverseSteps(next,count);if(kind==='humanize')next=humanizeSteps(next,8);if(kind==='quantize')next=quantizeVelocity(next,.75,100);await session.applySteps(next);}setProgress('Done');}catch(e){setProgress(e instanceof Error?e.message:'Failed');}}
 async function region(kind:'duplicate'|'clear'){if(isDrums)return;saveUndo();const a=Math.max(0,Math.min(count-1,from-1)),b=Math.max(a,Math.min(count-1,to-1));const next=kind==='duplicate'?duplicateRange(state.steps,a,b,Math.max(0,destination-1),count):clearRange(state.steps,a,b);await session.applySteps(next);setProgress(kind==='duplicate'?'Region duplicated':'Region cleared');}
 async function undo(){const previous=undoRef.current.pop();if(!previous)return;setProgress('Undo…');if(isDrums)await session.applyDrumSteps(previous.drums);else await session.applySteps(previous.synth);setProgress('Undone');}
 function download(name:string,data:BlobPart,type:string){const url=URL.createObjectURL(new Blob([data],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 async function importFile(file:File){saveUndo();setProgress(`Importing ${file.name}…`);if(/\.mid(i)?$/i.test(file.name)||file.type.includes('midi')){if(isDrums)throw new Error('MIDI note import targets synth tracks.');await session.applySteps(midiToSequence(await file.arrayBuffer(),count));}else{const parsed=importSequenceJson(await file.text());if(isDrums&&parsed.drums.length)await session.applyDrumSteps(parsed.drums);else if(!isDrums&&parsed.synth.length)await session.applySteps(parsed.synth);}setProgress('Imported');}
 function setProbability(value:number){setProbabilityState(value);setTrackProbability(state.selectedTrack,value/100);}
 return <section className="hardware-panel sequence-shell rounded-xl" id="sequence">
  <div className="sequence-header"><div><b>Pattern Sequencer</b><div className="text-[9px] text-zinc-500">Choose a track, paint a 16-step page, then fine-tune only what you select.</div></div><div className="sequence-track-tabs">{state.tracks.map((track,index)=><button key={track.index} className={index===state.selectedTrack?'active':''} onClick={()=>void session.selectTrack(index)}>{TRACKS[index]}</button>)}</div><div className="ml-auto flex gap-1">{!isDrums&&<><button onClick={()=>setView('steps')} className={`tool ${view==='steps'?'border-emerald-300/40 text-emerald-200':''}`}>STEPS</button><button onClick={()=>setView('piano')} className={`tool ${view==='piano'?'border-emerald-300/40 text-emerald-200':''}`}>PIANO</button></>}{virtual?<button onClick={onTogglePlay} className={`rounded px-3 py-1.5 text-xs font-black ${playing?'bg-amber-300 text-black':'bg-emerald-300 text-black'}`}>{playing?<><Pause size={12} className="mr-1 inline"/>PAUSE</>:<><Play size={12} className="mr-1 inline"/>PLAY</>}</button>:<span className="tool"><Square size={11}/>FM-1 TRANSPORT</span>}<button className="tool" onClick={()=>void session.refreshSequence()}><RefreshCw size={11}/></button></div></div>
  <div className="sequence-composebar"><div><div className="field">PAGE</div><div className="sequence-bank-tabs">{Array.from({length:banks},(_,i)=><button key={i} className={safeBank===i?'active':''} onClick={()=>{setBank(i);setSelected(null);}}>{i*16+1}–{Math.min(count,i*16+16)}</button>)}</div></div>{isDrums?<><label className="field">HIT LEVEL<select className="select" value={drumLevel} onChange={e=>setDrumLevel(Number(e.target.value))}><option value={0}>Ghost</option><option value={1}>Soft</option><option value={2}>Normal</option><option value={3}>Hard</option></select></label><label className="field">RATCHET<select className="select" value={drumRatchet} onChange={e=>setDrumRatchet(Number(e.target.value))}><option value={0}>Off</option><option value={1}>2×</option><option value={2}>3×</option><option value={3}>4×</option></select></label></>:<><label className="field">PAINT NOTE<select className="select" value={insertNote} onChange={e=>setInsertNote(Number(e.target.value))}>{notes(36,84).map(n=><option key={n} value={n}>{noteName(n)}</option>)}</select></label><button className="tool" onClick={()=>onAudition(insertNote)}>AUDITION</button></>}{virtual&&<label className="field min-w-36">PROBABILITY {probability}%<input type="range" min={0} max={100} value={probability} onChange={e=>setProbability(Number(e.target.value))}/></label>}<div className="sequence-help">Click = paint/remove · selected step opens below · page tabs keep the pattern compact.</div></div>
  {isDrums?<DrumBank state={state} session={session} first={first} visible={visible} playhead={playhead} level={drumLevel} ratchet={drumRatchet}/>:view==='piano'?<PianoBank state={state} session={session} first={first} visible={visible} playhead={playhead}/>:<SynthBank state={state} session={session} first={first} visible={visible} playhead={playhead} insertNote={insertNote} selected={selected} setSelected={setSelected} onAudition={onAudition}/>} 
  {!isDrums&&view==='steps'&&selected!==null&&<StepInspector state={state} session={session} index={selected} fallbackNote={insertNote}/>} 
  <details className="sequence-advanced"><summary>ADVANCED PATTERN TOOLS · transforms · region · import/export</summary><div className="mt-2 flex flex-wrap items-end gap-1"><button onClick={()=>void transform('rotateL')} className="tool">← Rotate</button><button onClick={()=>void transform('rotateR')} className="tool">Rotate →</button><button onClick={()=>void transform('reverse')} className="tool"><RotateCcw size={11}/>Reverse</button>{!isDrums&&<><button onClick={()=>void transform('humanize')} className="tool">Humanize</button><button onClick={()=>void transform('quantize')} className="tool">Velocity quantize</button><label className="field ml-2">From<input className="input w-14" type="number" min={1} max={count} value={from} onChange={e=>setFrom(Number(e.target.value))}/></label><label className="field">To<input className="input w-14" type="number" min={1} max={count} value={to} onChange={e=>setTo(Number(e.target.value))}/></label><label className="field">Paste at<input className="input w-16" type="number" min={1} max={count} value={destination} onChange={e=>setDestination(Number(e.target.value))}/></label><button onClick={()=>void region('duplicate')} className="tool">Duplicate</button><button onClick={()=>void region('clear')} className="tool">Clear</button></>}<button disabled={!undoRef.current.length} onClick={()=>void undo()} className="tool disabled:opacity-30"><Undo2 size={11}/>Undo</button><button onClick={()=>download('sloop-sequence.json',exportSequenceJson({synth:state.steps,drums:state.drumSteps}),'application/json')} className="tool"><Download size={11}/>JSON</button>{!isDrums&&<button onClick={()=>download('sloop-sequence.mid',sequenceToMidi(state.steps,bpm),'audio/midi')} className="tool">MIDI</button>}<label className="tool cursor-pointer"><Upload size={11}/>Import<input type="file" accept="application/json,.json,audio/midi,.mid,.midi" className="hidden" onChange={e=>{const f=e.target.files?.[0];if(f)void importFile(f).catch(err=>setProgress(err instanceof Error?err.message:'Import failed'));}}/></label><span className="ml-2 self-center text-[9px] text-zinc-600">{progress}</span></div></details>
 </section>;
}

function SynthBank({state,session,first,visible,playhead,insertNote,selected,setSelected,onAudition}:{state:SessionState;session:SloopDeviceSession;first:number;visible:number;playhead:number;insertNote:number;selected:number|null;setSelected:(v:number)=>void;onAudition:(note:number)=>void}){async function toggle(index:number){const current=state.steps.find(s=>s.index===index);if(current?.notes.length)await session.setStep({...current,notes:[],time:2});else await session.toggleStep(index,insertNote);setSelected(index);}return <div className="step-row">{Array.from({length:visible},(_,local)=>{const index=first+local,step=state.steps.find(s=>s.index===index),active=!!step?.notes.length;return <button key={index} onClick={()=>void toggle(index)} onContextMenu={e=>{e.preventDefault();setSelected(index);step?.notes.forEach(onAudition);}} className={`step-pad ${active?'active':''} ${selected===index?'selected':''} ${playhead===index?'playing':''}`}><span className="step-number">{index+1}</span><span className="step-note">{active?step!.notes.map(noteName).join('·'):'+'}</span>{active&&step?.ratchet?<span className="step-ratchet">×{step.ratchet+1}</span>:null}</button>;})}</div>;}
function StepInspector({state,session,index,fallbackNote}:{state:SessionState;session:SloopDeviceSession;index:number;fallbackNote:number}){const step=state.steps.find(s=>s.index===index)??{index,notes:[fallbackNote],time:0 as const,flags:0,velocity:100,level:100,ratchet:0};async function patch(patch:Partial<StepData>){await session.setStep({...step,...patch});}return <div className="step-inspector"><div><div className="field">STEP</div><b>{index+1}</b></div><label className="field">NOTES · MAX 4<input className="input" value={step.notes.map(noteName).join(' ')} onChange={e=>{const parsed=parseNotes(e.target.value).slice(0,4);void patch({notes:parsed,time:parsed.length?0:2});}}/></label><label className="field">VELOCITY {step.velocity}<input type="range" min={1} max={127} value={step.velocity} onChange={e=>void patch({velocity:Number(e.target.value)})}/></label><label className="field">LEVEL {step.level}<input type="range" min={0} max={255} value={step.level} onChange={e=>void patch({level:Number(e.target.value)})}/></label><label className="field">RATCHET<select className="select" value={step.ratchet} onChange={e=>void patch({ratchet:Number(e.target.value)})}><option value={0}>Off</option><option value={1}>2×</option><option value={2}>3×</option><option value={3}>4×</option></select></label><div className="flex gap-1"><button onClick={()=>void patch({flags:step.flags^1})} className={`tool ${step.flags&1?'text-amber-200':''}`}>ACC</button><button onClick={()=>void patch({flags:step.flags^2})} className={`tool ${step.flags&2?'text-cyan-200':''}`}>SLIDE</button></div></div>;}
function DrumBank({state,session,first,visible,playhead,level,ratchet}:{state:SessionState;session:SloopDeviceSession;first:number;visible:number;playhead:number;level:number;ratchet:number}){return <div className="overflow-auto"><div className="min-w-[900px]">{Array.from({length:16},(_,lane)=><div key={lane} className="drum-row-new"><span className="py-2 text-[9px] font-bold text-zinc-500">PAD {String(lane+1).padStart(2,'0')}</span>{Array.from({length:visible},(_,local)=>{const index=first+local,step=state.drumSteps.find(s=>s.index===index),on=step?.on[lane]??false;return <button key={index} title={`Pad ${lane+1} · step ${index+1}`} onClick={()=>void session.setDrumLane(index,lane,!on,level,ratchet)} className={`drum-pad-new ${on?'active':''} ${playhead===index?'playing':''}`}>{on?'●':'·'}</button>;})}</div>)}</div></div>;}
function PianoBank({state,session,first,visible,playhead}:{state:SessionState;session:SloopDeviceSession;first:number;visible:number;playhead:number}){const pitches=notes(48,73).reverse();return <div className="piano-bank"><div className="min-w-[650px]">{pitches.map(note=><div key={note} className="piano-row-new"><span className="piano-key-new">{noteName(note)}</span>{Array.from({length:visible},(_,local)=>{const index=first+local,step=state.steps.find(s=>s.index===index),active=step?.notes.includes(note);return <button key={index} title={`${noteName(note)} · step ${index+1}`} onClick={()=>{const current=step??{index,notes:[],time:2 as const,flags:0,velocity:100,level:100,ratchet:0};const list=active?current.notes.filter(n=>n!==note):[...current.notes,note].slice(0,4);void session.setStep({...current,notes:list,time:list.length?0:2});}} className={`piano-cell-new ${active?'active':''} ${playhead===index?'ring-1 ring-white':''}`}/>;})}</div>)}</div></div>;}
function notes(from:number,to:number){return Array.from({length:to-from},(_,i)=>from+i);}function noteName(note:number){const names=['C','C#','D','D#','E','F','F#','G','G#','A','A#','B'];return`${names[note%12]}${Math.floor(note/12)-1}`;}function parseNotes(value:string){const names:Record<string,number>={C:0,'C#':1,DB:1,D:2,'D#':3,EB:3,E:4,F:5,'F#':6,GB:6,G:7,'G#':8,AB:8,A:9,'A#':10,BB:10,B:11};return value.trim().split(/[ ,]+/).map(token=>{if(/^\d+$/.test(token))return Number(token);const m=/^([A-Ga-g])([#b]?)(-?\d)$/.exec(token);if(!m)return-1;const key=m[1].toUpperCase()+(m[2]?m[2].toUpperCase():'');return(names[key]??-99)+(Number(m[3])+1)*12;}).filter(n=>n>=0&&n<=127);}
