import { Download, Pause, Play, RefreshCw, RotateCcw, Square, Undo2, Upload } from 'lucide-react';
import { useEffect, useRef, useState } from 'react';
import type { DrumStepData, SessionState, SloopDeviceSession, StepData } from '../../core/SloopDeviceSession';
import type { VirtualSloopTransport } from '../../core/VirtualSloopTransport';
import { clearRange, duplicateRange, exportSequenceJson, humanizeSteps, importSequenceJson, midiToSequence, quantizeVelocity, reverseDrums, reverseSteps, rotateDrums, rotateSteps, sequenceToMidi } from '../../features/sequencer/sequenceTools';
import { getTrackProbability, getTrackSequenceLength, setTrackProbability, setTrackSequenceLength } from '../../features/sequencer/sequenceRuntime';
import { EditablePianoRoll } from './EditablePianoRoll';

const TRACKS=['SYNTH 1','SYNTH 2','SYNTH 3','DRUMS'];
const DRUM_NAMES=['Kick','Kick 2','Snare','Clap','Hat','Open Hat','Pedal','Rim','Snare 2','Low Tom','Hi Tom','Crash','Ride','Shaker','Conga','Cowbell'];
const CHORDS:{name:string;intervals:number[]}[]=[{name:'NOTE',intervals:[0]},{name:'MAJOR',intervals:[0,4,7]},{name:'MINOR',intervals:[0,3,7]},{name:'7TH',intervals:[0,4,7,10]},{name:'MIN7',intervals:[0,3,7,10]},{name:'SUS2',intervals:[0,2,7]},{name:'SUS4',intervals:[0,5,7]},{name:'POWER',intervals:[0,7,12]},{name:'OCTAVE',intervals:[0,12]}];
type Props={state:SessionState;session:SloopDeviceSession;virtual:boolean;virtualTransport?:VirtualSloopTransport;playing:boolean;playhead:number;playAllTracks:boolean;onPlayAllTracksChange:(value:boolean)=>void;onTogglePlay:()=>void;onAudition:(note:number)=>void};

export function Sequencer({state,session,virtual,virtualTransport,playing,playhead,playAllTracks,onPlayAllTracksChange,onTogglePlay,onAudition}:Props){
 const maximum=state.info?.stepCount??64,isDrums=state.selectedTrack===3;
 const[trackLength,setTrackLength]=useState(()=>getTrackSequenceLength(state.selectedTrack,maximum));
 const banks=Math.max(1,Math.ceil(trackLength/16));
 const[bank,setBank]=useState(0),[view,setView]=useState<'steps'|'piano'>('steps'),[progress,setProgress]=useState(''),[insertNote,setInsertNote]=useState(60),[chord,setChord]=useState('NOTE'),[selected,setSelected]=useState<number|null>(null),[from,setFrom]=useState(1),[to,setTo]=useState(Math.min(16,trackLength)),[destination,setDestination]=useState(Math.min(17,trackLength)),[probability,setProbabilityState]=useState(Math.round(getTrackProbability(state.selectedTrack)*100)),[drumLevel,setDrumLevel]=useState(2),[drumRatchet,setDrumRatchet]=useState(0),[drumNames,setDrumNames]=useState<string[]>(DRUM_NAMES);
 const undoRef=useRef<Array<{synth:StepData[];drums:DrumStepData[]}>>([]),safeBank=Math.min(bank,banks-1),first=safeBank*16,visible=Math.min(16,trackLength-first);
 const bpmDescriptor=state.descriptors.find(d=>d.scope===1&&d.label.toUpperCase()==='BPM'),bpm=bpmDescriptor?state.values[`1:${bpmDescriptor.id}`]??120:120;
 useEffect(()=>{const next=getTrackSequenceLength(state.selectedTrack,maximum);setTrackLength(next);setBank(0);setSelected(null);setTo(Math.min(16,next));setDestination(Math.min(17,next));setProbabilityState(Math.round(getTrackProbability(state.selectedTrack)*100));},[state.selectedTrack,maximum]);
 useEffect(()=>{const handler=()=>void undo();window.addEventListener('sloopui:undo',handler);return()=>window.removeEventListener('sloopui:undo',handler);});
 function changeLength(value:number){const next=setTrackSequenceLength(state.selectedTrack,value,maximum);setTrackLength(next);setBank(current=>Math.min(current,Math.ceil(next/16)-1));setSelected(current=>current!=null&&current>=next?null:current);setTo(current=>Math.min(current,next));setDestination(current=>Math.min(current,next));setProgress(`Track length: ${next} steps`);}
 function saveUndo(){undoRef.current.push({synth:state.steps.map(s=>({...s,notes:[...s.notes]})),drums:state.drumSteps.map(s=>({...s,on:[...s.on],levels:[...s.levels],ratchets:[...s.ratchets]}))});if(undoRef.current.length>20)undoRef.current.shift();}
 async function transform(kind:'rotateL'|'rotateR'|'reverse'|'humanize'|'quantize'){saveUndo();setProgress('Applying…');try{if(isDrums){let next=state.drumSteps;if(kind==='rotateL')next=rotateDrums(next,-1,trackLength);if(kind==='rotateR')next=rotateDrums(next,1,trackLength);if(kind==='reverse')next=reverseDrums(next,trackLength);await session.applyDrumSteps(next.filter(s=>s.index<trackLength));}else{let next=state.steps;if(kind==='rotateL')next=rotateSteps(next,-1,trackLength);if(kind==='rotateR')next=rotateSteps(next,1,trackLength);if(kind==='reverse')next=reverseSteps(next,trackLength);if(kind==='humanize')next=humanizeSteps(next,8);if(kind==='quantize')next=quantizeVelocity(next,.75,100);await session.applySteps(next.filter(s=>s.index<trackLength));}setProgress('Done');}catch(e){setProgress(e instanceof Error?e.message:'Failed');}}
 async function region(kind:'duplicate'|'clear'){if(isDrums)return;saveUndo();const a=Math.max(0,Math.min(trackLength-1,from-1)),b=Math.max(a,Math.min(trackLength-1,to-1));const next=kind==='duplicate'?duplicateRange(state.steps,a,b,Math.max(0,destination-1),maximum):clearRange(state.steps,a,b);await session.applySteps(next.filter(s=>s.index<maximum));setProgress(kind==='duplicate'?'Region duplicated':'Region cleared');}
 async function undo(){const previous=undoRef.current.pop();if(!previous)return;setProgress('Undo…');if(isDrums)await session.applyDrumSteps(previous.drums);else await session.applySteps(previous.synth);setProgress('Undone');}
 function download(name:string,data:BlobPart,type:string){const url=URL.createObjectURL(new Blob([data],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 async function importFile(file:File){saveUndo();setProgress(`Importing ${file.name}…`);if(/\.mid(i)?$/i.test(file.name)||file.type.includes('midi')){if(isDrums)throw new Error('MIDI note import targets synth tracks.');await session.applySteps(midiToSequence(await file.arrayBuffer(),maximum));}else{const parsed=importSequenceJson(await file.text());if(isDrums&&parsed.drums.length)await session.applyDrumSteps(parsed.drums);else if(!isDrums&&parsed.synth.length)await session.applySteps(parsed.synth);}setProgress('Imported');}
 function setProbability(value:number){setProbabilityState(value);setTrackProbability(state.selectedTrack,value/100);}
 async function applyPreset(name:string){saveUndo();setProgress(`Loading ${name}…`);try{if(isDrums)await session.applyDrumSteps(makeDrumPreset(name,maximum));else await session.applySteps(makeSynthPreset(name,maximum,insertNote));setProgress(`${name} ready`);}catch(e){setProgress(e instanceof Error?e.message:'Preset failed');}}
 async function mapDrum(lane:number,file:File){if(!virtualTransport)return;const ctx=new AudioContext();try{const buffer=await ctx.decodeAudioData(await file.arrayBuffer());await virtualTransport.loadDrumSample(lane,buffer);setDrumNames(current=>current.map((n,i)=>i===lane?strip(file.name):n));setProgress(`${strip(file.name)} mapped to pad ${lane+1}`);}finally{await ctx.close();}}
 const paintNotes=chordNotes(insertNote,chord);
 return <section className="hardware-panel sequence-shell rounded-xl" id="sequence">
  <div className="sequence-header"><div><b>Pattern Sequencer</b><div className="text-[9px] text-zinc-500">Single click selects/inserts. Double-click an active step to delete. Piano roll supports multi-select, move, resize and note effects.</div></div><div className="sequence-track-tabs">{state.tracks.map((track,index)=><button key={track.index} className={index===state.selectedTrack?'active':''} onClick={()=>void session.selectTrack(index)}>{TRACKS[index]}</button>)}</div><div className="ml-auto flex gap-1">{!isDrums&&<><button onClick={()=>setView('steps')} className={`tool ${view==='steps'?'border-emerald-300/40 text-emerald-200':''}`}>STEPS</button><button onClick={()=>setView('piano')} className={`tool ${view==='piano'?'border-emerald-300/40 text-emerald-200':''}`}>PIANO</button></>}{virtual&&<button className={`tool ${playAllTracks?'border-cyan-300/40 text-cyan-200':''}`} onClick={()=>onPlayAllTracksChange(!playAllTracks)}>{playAllTracks?'ALL TRACKS':'THIS TRACK'}</button>}{virtual?<button onClick={onTogglePlay} className={`rounded px-3 py-1.5 text-xs font-black ${playing?'bg-amber-300 text-black':'bg-emerald-300 text-black'}`}>{playing?<><Pause size={12} className="mr-1 inline"/>PAUSE</>:<><Play size={12} className="mr-1 inline"/>PLAY</>}</button>:<span className="tool"><Square size={11}/>FM-1 TRANSPORT</span>}<button className="tool" onClick={()=>void session.refreshSequence()}><RefreshCw size={11}/></button></div></div>
  <div className="sequence-composebar"><div><div className="field">PAGE</div><div className="sequence-bank-tabs">{Array.from({length:banks},(_,i)=><button key={i} className={safeBank===i?'active':''} onClick={()=>{setBank(i);setSelected(null);}}>{i*16+1}–{Math.min(trackLength,i*16+16)}</button>)}</div></div><div><div className="field">LENGTH</div><div className="flex items-center gap-1">{[8,16,32,48,64].filter(x=>x<=maximum).map(x=><button key={x} className={`tool ${trackLength===x?'border-emerald-300/40 text-emerald-200':''}`} onClick={()=>changeLength(x)}>{x}</button>)}<input className="input w-14" type="number" min={1} max={maximum} value={trackLength} onChange={e=>changeLength(Number(e.target.value))}/></div></div>{isDrums?<><label className="field">HIT LEVEL<select className="select" value={drumLevel} onChange={e=>setDrumLevel(Number(e.target.value))}><option value={0}>Ghost</option><option value={1}>Soft</option><option value={2}>Normal</option><option value={3}>Hard</option></select></label><label className="field">RATCHET<select className="select" value={drumRatchet} onChange={e=>setDrumRatchet(Number(e.target.value))}><option value={0}>Off</option><option value={1}>2×</option><option value={2}>3×</option><option value={3}>4×</option></select></label><label className="field">PATTERN<select className="select" defaultValue="" onChange={e=>{if(e.target.value)void applyPreset(e.target.value);e.currentTarget.value='';}}><option value="">Choose preset…</option>{['EMPTY','FOUR FLOOR','HOUSE','BREAK','TRAP','DNB'].map(x=><option key={x}>{x}</option>)}</select></label></>:<><label className="field">ROOT<select className="select" value={insertNote} onChange={e=>setInsertNote(Number(e.target.value))}>{notes(36,84).map(n=><option key={n} value={n}>{noteName(n)}</option>)}</select></label><label className="field">INSERT<select className="select" value={chord} onChange={e=>setChord(e.target.value)}>{CHORDS.map(c=><option key={c.name}>{c.name}</option>)}</select></label><button className="tool" onClick={()=>paintNotes.forEach(onAudition)}>AUDITION {paintNotes.map(noteName).join(' ')}</button><label className="field">PATTERN<select className="select" defaultValue="" onChange={e=>{if(e.target.value)void applyPreset(e.target.value);e.currentTarget.value='';}}><option value="">Choose preset…</option>{['EMPTY','PULSE BASS','OFFBEAT','ARP UP','ARP DOWN','CHORD STABS'].map(x=><option key={x}>{x}</option>)}</select></label></>}{virtual&&<label className="field min-w-32">PROB {probability}%<input type="range" min={0} max={100} value={probability} onChange={e=>setProbability(Number(e.target.value))}/></label>}<div className="sequence-help">Wheel = ±1 semitone · Shift+wheel = ±1 octave.</div></div>
  {isDrums?<DrumBank state={state} session={session} first={first} visible={visible} playhead={playhead} level={drumLevel} ratchet={drumRatchet} virtual={virtual} virtualTransport={virtualTransport} names={drumNames} onMap={mapDrum}/>:view==='piano'?<EditablePianoRoll state={state} session={session} first={first} visible={visible} playhead={playhead}/>:<SynthBank state={state} session={session} first={first} visible={visible} playhead={playhead} paintNotes={paintNotes} selected={selected} setSelected={setSelected}/>} 
  {!isDrums&&view==='steps'&&selected!==null&&<StepInspector state={state} session={session} index={selected} fallbackNote={insertNote} onDeleted={()=>setSelected(null)}/>} 
  <details className="sequence-advanced"><summary>ADVANCED PATTERN TOOLS · transforms · region · import/export</summary><div className="mt-2 flex flex-wrap items-end gap-1"><button onClick={()=>void transform('rotateL')} className="tool">← Rotate</button><button onClick={()=>void transform('rotateR')} className="tool">Rotate →</button><button onClick={()=>void transform('reverse')} className="tool"><RotateCcw size={11}/>Reverse</button>{!isDrums&&<><button onClick={()=>void transform('humanize')} className="tool">Humanize</button><button onClick={()=>void transform('quantize')} className="tool">Velocity quantize</button><label className="field ml-2">From<input className="input w-14" type="number" min={1} max={trackLength} value={from} onChange={e=>setFrom(Number(e.target.value))}/></label><label className="field">To<input className="input w-14" type="number" min={1} max={trackLength} value={to} onChange={e=>setTo(Number(e.target.value))}/></label><label className="field">Paste at<input className="input w-16" type="number" min={1} max={trackLength} value={destination} onChange={e=>setDestination(Number(e.target.value))}/></label><button onClick={()=>void region('duplicate')} className="tool">Duplicate</button><button onClick={()=>void region('clear')} className="tool">Clear</button></>}<button disabled={!undoRef.current.length} onClick={()=>void undo()} className="tool disabled:opacity-30"><Undo2 size={11}/>Undo</button><button onClick={()=>download('sloop-sequence.json',exportSequenceJson({synth:state.steps,drums:state.drumSteps}),'application/json')} className="tool"><Download size={11}/>JSON</button>{!isDrums&&<button onClick={()=>download('sloop-sequence.mid',sequenceToMidi(state.steps,bpm),'audio/midi')} className="tool">MIDI</button>}<label className="tool cursor-pointer"><Upload size={11}/>Import<input type="file" accept="application/json,.json,audio/midi,.mid,.midi" className="hidden" onChange={e=>{const f=e.target.files?.[0];if(f)void importFile(f).catch(err=>setProgress(err instanceof Error?err.message:'Import failed'));}}/></label><span className="ml-2 self-center text-[9px] text-zinc-600">{progress}</span></div></details>
 </section>;
}

function SynthBank({state,session,first,visible,playhead,paintNotes,selected,setSelected}:{state:SessionState;session:SloopDeviceSession;first:number;visible:number;playhead:number;paintNotes:number[];selected:number|null;setSelected:(v:number)=>void}){const paint=useRef(false);usePaintRelease(paint);async function insert(index:number){const current=state.steps.find(s=>s.index===index)??emptyStep(index);if(current.notes.length){setSelected(index);return;}await session.setStep({...current,notes:paintNotes,time:0,velocity:current.velocity||100,level:current.level||100});setSelected(index);}async function remove(index:number){const current=state.steps.find(s=>s.index===index);if(!current?.notes.length)return;await session.setStep({...current,notes:[],time:2});if(selected===index)setSelected(index);}async function transpose(index:number,delta:number){const current=state.steps.find(s=>s.index===index);if(!current?.notes.length)return;await session.setStep({...current,notes:current.notes.map(n=>Math.max(0,Math.min(127,n+delta)))});setSelected(index);}return <div className="step-row">{Array.from({length:visible},(_,local)=>{const index=first+local,step=state.steps.find(s=>s.index===index),active=!!step?.notes.length;return <button key={index} onPointerDown={e=>{e.preventDefault();if(active){paint.current=false;setSelected(index);}else{paint.current=true;void insert(index);}}} onPointerEnter={()=>{if(paint.current&&!active)void insert(index);}} onDoubleClick={e=>{e.preventDefault();if(active)void remove(index);}} onWheel={e=>{if(!active)return;e.preventDefault();void transpose(index,(e.shiftKey?12:1)*(e.deltaY>0?-1:1));}} onContextMenu={e=>{e.preventDefault();setSelected(index);}} title={active?'Click select · double-click delete · wheel transpose':'Click/drag to insert'} className={`step-pad ${active?'active':''} ${selected===index?'selected':''} ${playhead===index?'playing':''}`}><span className="step-number">{index+1}</span><span className="step-note">{active?step!.notes.map(noteName).join('·'):'+'}</span>{active&&step?.ratchet?<span className="step-ratchet">×{step.ratchet+1}</span>:null}</button>;})}</div>;}
function StepInspector({state,session,index,fallbackNote,onDeleted}:{state:SessionState;session:SloopDeviceSession;index:number;fallbackNote:number;onDeleted:()=>void}){const step=state.steps.find(s=>s.index===index)??{...emptyStep(index),notes:[fallbackNote],time:0 as const};async function patch(patch:Partial<StepData>){await session.setStep({...step,...patch});}async function remove(){await patch({notes:[],time:2});onDeleted();}return <div className="step-inspector"><div><div className="field">STEP</div><b>{index+1}</b></div><label className="field">NOTES · MAX 4<input className="input" value={step.notes.map(noteName).join(' ')} onChange={e=>{const parsed=parseNotes(e.target.value).slice(0,4);void patch({notes:parsed,time:parsed.length?0:2});}}/></label><div className="flex flex-wrap gap-1"><span className="field self-center">CHORD</span>{CHORDS.slice(1).map(c=><button key={c.name} className="tool" onClick={()=>void patch({notes:c.intervals.map(i=>Math.min(127,fallbackNote+i)).slice(0,4),time:0})}>{c.name}</button>)}</div><label className="field">VELOCITY {step.velocity}<input type="range" min={1} max={127} value={step.velocity} onChange={e=>void patch({velocity:Number(e.target.value)})}/></label><label className="field">LEVEL {step.level}<input type="range" min={0} max={255} value={step.level} onChange={e=>void patch({level:Number(e.target.value)})}/></label><label className="field">RATCHET<select className="select" value={step.ratchet} onChange={e=>void patch({ratchet:Number(e.target.value)})}><option value={0}>Off</option><option value={1}>2×</option><option value={2}>3×</option><option value={3}>4×</option></select></label><div className="flex gap-1"><button onClick={()=>void patch({flags:step.flags^1})} className={`tool ${step.flags&1?'text-amber-200':''}`}>ACC</button><button onClick={()=>void patch({flags:step.flags^2})} className={`tool ${step.flags&2?'text-cyan-200':''}`}>SLIDE</button><button onClick={()=>void remove()} className="tool text-rose-300">DELETE STEP</button></div></div>;}
function DrumBank({state,session,first,visible,playhead,level,ratchet,virtual,virtualTransport,names,onMap}:{state:SessionState;session:SloopDeviceSession;first:number;visible:number;playhead:number;level:number;ratchet:number;virtual:boolean;virtualTransport?:VirtualSloopTransport;names:string[];onMap:(lane:number,file:File)=>Promise<void>}){const paint=useRef<boolean|null>(null);usePaintRelease(paint);async function set(index:number,lane:number,on:boolean){await session.setDrumLane(index,lane,on,level,ratchet);}return <div className="overflow-auto"><div className="min-w-[980px]">{Array.from({length:16},(_,lane)=><div key={lane} className="drum-row-new" style={{gridTemplateColumns:'150px repeat(16,1fr)'}}><div className="flex items-center gap-1 pr-2"><button className="min-w-0 flex-1 truncate text-left text-[9px] font-bold text-zinc-400" title={virtual?'Click to audition mapped/default sound':'FM-1 lane sound is defined by the selected kit'} onClick={()=>virtualTransport?.triggerDrumSample(lane)}>{String(lane+1).padStart(2,'0')} · {names[lane]}</button>{virtual&&<label className="tool cursor-pointer px-1.5 py-1 text-[8px]">MAP<input className="hidden" type="file" accept="audio/*" onChange={e=>{const f=e.target.files?.[0];if(f)void onMap(lane,f);e.currentTarget.value='';}}/></label>}</div>{Array.from({length:visible},(_,local)=>{const index=first+local,step=state.drumSteps.find(s=>s.index===index),on=step?.on[lane]??false;return <button key={index} title={`${names[lane]} · step ${index+1}`} onPointerDown={e=>{e.preventDefault();paint.current=!on;void set(index,lane,!on);}} onPointerEnter={()=>{if(paint.current!==null)void set(index,lane,paint.current);}} className={`drum-pad-new ${on?'active':''} ${playhead===index?'playing':''}`}>{on?'●':'·'}</button>;})}</div>)}</div>{!virtual&&<div className="mt-2 text-[9px] text-zinc-600">Hardware lane sounds come from the FM-1 drum kit. Individual lane sample mapping is virtual-only.</div>}</div>;}
function usePaintRelease(ref:React.MutableRefObject<any>){useEffect(()=>{const stop=()=>{ref.current=null;};window.addEventListener('pointerup',stop);window.addEventListener('pointercancel',stop);return()=>{window.removeEventListener('pointerup',stop);window.removeEventListener('pointercancel',stop);};},[ref]);}
function chordNotes(root:number,name:string){const intervals=CHORDS.find(c=>c.name===name)?.intervals??[0];return intervals.map(i=>Math.min(127,root+i)).slice(0,4);}
function emptyStep(index:number):StepData{return{index,notes:[],time:2,flags:0,velocity:100,level:100,ratchet:0};}
function makeSynthPreset(name:string,count:number,root:number){const out=Array.from({length:count},(_,index)=>emptyStep(index));const put=(i:number,ints:number[],vel=105)=>{if(i<count)out[i]={...emptyStep(i),notes:ints.map(x=>Math.min(127,root+x)).slice(0,4),time:0,velocity:vel};};if(name==='PULSE BASS')for(let i=0;i<count;i+=4)put(i,[0]);if(name==='OFFBEAT')for(let i=2;i<count;i+=4)put(i,[0]);if(name==='ARP UP')for(let i=0;i<count;i+=2)put(i,[[0,4,7,12][(i/2)%4]]);if(name==='ARP DOWN')for(let i=0;i<count;i+=2)put(i,[[12,7,4,0][(i/2)%4]]);if(name==='CHORD STABS')for(let i=0;i<count;i+=8)put(i,[0,4,7],112);return out;}
function makeDrumPreset(name:string,count:number){const out:Array<DrumStepData>=Array.from({length:count},(_,index)=>({index,on:Array(16).fill(false),levels:Array(16).fill(2),ratchets:Array(16).fill(0)}));const hit=(step:number,lane:number,level=2,ratchet=0)=>{if(step>=count)return;out[step].on[lane]=true;out[step].levels[lane]=level;out[step].ratchets[lane]=ratchet;};if(name==='FOUR FLOOR'||name==='HOUSE')for(let i=0;i<count;i+=4)hit(i,0,3);if(name==='HOUSE'){for(let i=2;i<count;i+=4)hit(i,4);for(let i=4;i<count;i+=8)hit(i,2,3);}if(name==='BREAK'){for(let b=0;b<count;b+=16){[0,6,10].forEach(s=>hit(b+s,0,3));[4,12].forEach(s=>hit(b+s,2,3));for(let s=0;s<16;s+=2)hit(b+s,4,1);}}if(name==='TRAP'){for(let b=0;b<count;b+=16){[0,7,10].forEach(s=>hit(b+s,0,3));[4,12].forEach(s=>hit(b+s,2,3));for(let s=0;s<16;s+=2)hit(b+s,4,1,s===14?2:0);}}if(name==='DNB'){for(let b=0;b<count;b+=16){[0,10].forEach(s=>hit(b+s,0,3));[4,12].forEach(s=>hit(b+s,2,3));for(let s=0;s<16;s+=2)hit(b+s,4,2);}}return out;}
function notes(from:number,to:number){return Array.from({length:to-from},(_,i)=>from+i);}function noteName(note:number){const names=['C','C#','D','D#','E','F','F#','G','G#','A','A#','B'];return`${names[note%12]}${Math.floor(note/12)-1}`;}function parseNotes(value:string){const names:Record<string,number>={C:0,'C#':1,DB:1,D:2,'D#':3,EB:3,E:4,F:5,'F#':6,GB:6,G:7,'G#':8,AB:8,A:9,'A#':10,BB:10,B:11};return value.trim().split(/[ ,]+/).map(token=>{if(/^\d+$/.test(token))return Number(token);const m=/^([A-Ga-g])([#b]?)(-?\d)$/.exec(token);if(!m)return-1;const key=m[1].toUpperCase()+(m[2]?m[2].toUpperCase():'');return(names[key]??-99)+(Number(m[3])+1)*12;}).filter(n=>n>=0&&n<=127);}function strip(name:string){return name.replace(/\.[^.]+$/,'').slice(0,18)||'sample';}
