import type { ParameterDescriptor, SessionState } from '../../core/SloopDeviceSession';

const W=220,H=86;
export type SynthVisualKind='filter'|'adsr'|'lfo';
export function SynthVisualizer({state,kind}:{state:SessionState;kind:SynthVisualKind}){if(kind==='adsr')return <AdsrScope state={state}/>;if(kind==='lfo')return <LfoScope state={state}/>;return <FilterScope state={state}/>;}
function LfoScope({state}:{state:SessionState}){const rate=findValue(state,['RATE']),wave=findDescriptor(state,['WAVE']),phase=findValue(state,['PHS','PHASE']),fade=findValue(state,['FADE']);if(rate===undefined&&wave===undefined)return null;return <Scope title="LFO" hint={wave?.enumValues?.[Math.max(0,(valueOf(state,wave)-wave.min))]??'WAVE'}><LfoGraph rate={norm(rate)} wave={wave?valueOf(state,wave)-wave.min:0} phase={norm(phase)} fade={norm(fade)}/></Scope>}
function FilterScope({state}:{state:SessionState}){const cutoff=findValue(state,['CUT','CUTOFF','FLT','FILTER','TONE']),res=findValue(state,['RES','RESO','RESONANCE']);if(cutoff===undefined&&res===undefined)return null;return <Scope title="FILTER" hint={`cut ${percent(cutoff)} · res ${percent(res)}`}><FilterGraph cutoff={filterValue(cutoff)} resonance={norm(res)}/></Scope>}
function AdsrScope({state}:{state:SessionState}){const attack=findValue(state,['ATK','ATTACK']),decay=findValue(state,['DEC','DECAY']),sustain=findValue(state,['SUS','SUSTAIN']),release=findValue(state,['REL','RELEASE']);if([attack,decay,sustain,release].every(v=>v===undefined))return null;return <Scope title="AMP ENVELOPE" hint={`A ${percent(attack)} D ${percent(decay)} S ${percent(sustain)} R ${percent(release)}`}><AdsrGraph attack={norm(attack)} decay={norm(decay)} sustain={norm(sustain)} release={norm(release)}/></Scope>}
function Scope({title,hint,children}:{title:string;hint:string;children:React.ReactNode}){const id=`grid-${title.replace(/\W/g,'')}`;return <section className="synth-scope"><div className="synth-scope-head"><b>{title}</b><span>{hint}</span></div><div className="synth-scope-screen"><svg viewBox={`0 0 ${W} ${H}`} preserveAspectRatio="none" aria-label={`${title} visualization`}><defs><pattern id={id} width="22" height="21.5" patternUnits="userSpaceOnUse"><path d="M 22 0 L 0 0 0 21.5" fill="none" stroke="currentColor" strokeOpacity=".08" strokeWidth="1"/></pattern></defs><rect width={W} height={H} fill={`url(#${id})`}/>{children}</svg></div></section>}
function LfoGraph({rate,wave,phase,fade}:{rate:number;wave:number;phase:number;fade:number}){const cycles=1+rate*5,pts:string[]=[];for(let x=0;x<=W;x+=2){const t=x/W,angle=(t*cycles+phase)*Math.PI*2;let y=0;if(wave===1)y=2/Math.PI*Math.asin(Math.sin(angle));else if(wave===2)y=2*((t*cycles+phase)%1)-1;else if(wave===3)y=Math.sin(angle)>=0?1:-1;else if(wave===4)y=Math.sin((Math.floor(t*cycles*8)+phase*13)*17.31);else y=Math.sin(angle);const amp=fade<=.01?1:Math.min(1,t/fade);pts.push(`${x},${H/2-y*(H*.34)*amp}`);}return <><line x1="0" y1={H/2} x2={W} y2={H/2} className="scope-axis"/><polyline points={pts.join(' ')} className="scope-line"/></>}
function FilterGraph({cutoff,resonance}:{cutoff:number;resonance:number}){const fc=.08+.84*cutoff,pts:string[]=[];for(let x=0;x<=W;x+=2){const f=x/W,q=.8+resonance*8,d=Math.max(.012,Math.abs(f-fc)),lp=1/(1+Math.pow(f/Math.max(.02,fc),8)),peak=Math.exp(-d*q*12)*resonance*.42,amp=Math.min(1,lp+peak);pts.push(`${x},${H-8-amp*(H-18)}`);}return <><line x1="0" y1={H-8} x2={W} y2={H-8} className="scope-axis"/><polyline points={pts.join(' ')} className="scope-line"/><line x1={fc*W} y1="8" x2={fc*W} y2={H-8} className="scope-marker"/></>}
function AdsrGraph({attack,decay,sustain,release}:{attack:number;decay:number;sustain:number;release:number}){const a=12+attack*48,d=14+decay*44,r=14+release*48,s=.08+.9*sustain,total=a+d+50+r,scale=(W-12)/total,x0=6,x1=x0+a*scale,x2=x1+d*scale,x3=x2+50*scale,x4=W-6,y0=H-7,yPeak=9,ySus=y0-(y0-yPeak)*s;return <><line x1="5" y1={y0} x2={W-5} y2={y0} className="scope-axis"/><polyline points={`${x0},${y0} ${x1},${yPeak} ${x2},${ySus} ${x3},${ySus} ${x4},${y0}`} className="scope-line"/><circle cx={x1} cy={yPeak} r="2" className="scope-node"/><circle cx={x2} cy={ySus} r="2" className="scope-node"/><circle cx={x3} cy={ySus} r="2" className="scope-node"/></>}
function findDescriptor(state:SessionState,labels:string[]){const upper=labels.map(x=>x.toUpperCase());return state.descriptors.find(d=>d.scope===0&&upper.includes(d.label.toUpperCase()));}
function findValue(state:SessionState,labels:string[]){const d=findDescriptor(state,labels);return d?normalizeDescriptor(valueOf(state,d),d):undefined;}
function valueOf(state:SessionState,d:ParameterDescriptor){return state.values[`0:${d.id}`]??d.defaultValue;}
function normalizeDescriptor(value:number,d:ParameterDescriptor){return d.max===d.min?0:(value-d.min)/(d.max-d.min);}
function norm(v:number|undefined){return Math.max(0,Math.min(1,v??0));}function percent(v:number|undefined){return `${Math.round(norm(v)*100)}%`;}function filterValue(v:number|undefined){return norm(v===undefined ? .5 : v);}
