import { useState } from 'react';
import { Drum, Piano, Trash2, Upload } from 'lucide-react';
import type { VirtualSloopTransport } from '../../core/VirtualSloopTransport';

const ROOTS=['C1','C2','C3','C4','C5','A2','A3','A4'];
export function VirtualSampleMap({transport}:{transport:VirtualSloopTransport}){
 const[drumNames,setDrumNames]=useState<string[]>(Array(16).fill('')),[trackNames,setTrackNames]=useState<string[]>(Array(3).fill('')),[roots,setRoots]=useState(['C3','C3','C3']),[status,setStatus]=useState('');
 async function decode(file:File){const ctx=new AudioContext();try{return await ctx.decodeAudioData(await file.arrayBuffer());}finally{await ctx.close();}}
 async function loadDrum(lane:number,file:File){try{const buffer=await decode(file);await transport.loadDrumSample(lane,buffer);setDrumNames(current=>current.map((name,i)=>i===lane?file.name:name));setStatus(`Mapped ${file.name} to drum pad ${lane+1}`);}catch(e){setStatus(e instanceof Error?e.message:'Unable to map drum sample');}}
 async function loadTrack(track:number,file:File){try{const buffer=await decode(file);await transport.loadTrackSample(track,buffer,roots[track]);setTrackNames(current=>current.map((name,i)=>i===track?file.name:name));setStatus(`Mapped ${file.name} to synth track ${track+1} at ${roots[track]}`);}catch(e){setStatus(e instanceof Error?e.message:'Unable to map pitched sample');}}
 return <section className="hardware-panel rounded-xl p-3"><div className="mb-2 flex items-center justify-between border-b border-white/8 pb-2"><div><b>Virtual Sample Map</b><span className="ml-2 text-[10px] text-zinc-500">pitched instruments + 16 drum pads · included in virtual bounce</span></div><span className="text-[9px] text-zinc-500">{status}</span></div>
  <div className="mb-3 grid gap-2 lg:grid-cols-3">{trackNames.map((name,track)=><div key={track} className="rounded-lg border border-white/8 bg-black/20 p-2"><div className="mb-2 flex items-center gap-2"><Piano size={13} className="text-cyan-300"/><b className="text-[10px]">SYNTH {track+1}</b><span className="ml-auto max-w-[180px] truncate text-[8px] text-zinc-600" title={name}>{name||'internal engine'}</span></div><div className="flex items-end gap-1"><label className="field w-20">Root<select className="select" value={roots[track]} onChange={e=>{const root=e.target.value;setRoots(current=>current.map((v,i)=>i===track?root:v));}}>{ROOTS.map(root=><option key={root}>{root}</option>)}</select></label><label className="tool flex-1 cursor-pointer"><Upload size={10}/>{name?'REPLACE':'MAP SAMPLE'}<input className="hidden" type="file" accept="audio/*" onChange={e=>{const file=e.target.files?.[0];if(file)void loadTrack(track,file);e.currentTarget.value='';}}/></label><button title="Use internal synth engine" disabled={!name} className="tool" onClick={()=>{transport.clearTrackSample(track);setTrackNames(current=>current.map((v,i)=>i===track?'':v));setStatus(`Synth ${track+1} returned to internal engine`);}}><Trash2 size={10}/></button></div><button disabled={!name} onClick={()=>transport.audition(roots[track],'8n',track,.85)} className="mt-2 tool w-full disabled:opacity-30">AUDITION {roots[track]}</button></div>)}</div>
  <div className="mb-2 flex items-center gap-2"><Drum size={13} className="text-rose-300"/><b className="text-[10px]">DRUM PADS</b><span className="text-[9px] text-zinc-600">mapped players override the virtual drum voice per lane</span></div><div className="grid gap-1 sm:grid-cols-2 lg:grid-cols-4 2xl:grid-cols-8">{drumNames.map((name,lane)=><div key={lane} className="rounded border border-white/8 bg-black/20 p-2"><button aria-label={`Audition virtual pad ${lane+1}`} onClick={()=>transport.triggerDrumSample(lane)} disabled={!name} className="mb-1 flex h-8 w-full items-center justify-center rounded border border-white/10 disabled:opacity-30"><span className="text-[9px] font-black">PAD {lane+1}</span></button><div className="flex gap-1"><label className="tool min-w-0 flex-1 cursor-pointer px-1"><Upload size={9}/>{name?'REPLACE':'MAP'}<input className="hidden" type="file" accept="audio/*" onChange={e=>{const file=e.target.files?.[0];if(file)void loadDrum(lane,file);e.currentTarget.value='';}}/></label><button disabled={!name} className="tool px-2" title="Clear pad sample" onClick={()=>{transport.clearDrumSample(lane);setDrumNames(current=>current.map((v,i)=>i===lane?'':v));}}><Trash2 size={9}/></button></div><div className="mt-1 truncate text-[8px] text-zinc-600" title={name}>{name||'internal drum'}</div></div>)}</div>
 </section>;
}
